### ISSUE TITLE
Schedule initial project meeting with Jean Walsh

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#1]
_From @hackajesse on October 21, 2015 17:5_

_Copied from original issue: sfbrigade/adopt-a-drain.old#9_

**Comment by hackajesse** [comment]
Scheduled for Friday 10/30 at 10am. 
Meeting to get folks on the same page. 

Agenda:
1. Jason/Jean update on the status of opening the data
2. Jesse/Jason update Jean on the status of the app
3. Jean/PUC concerns/questions
4. Next steps discussion
5. Next meeting scheduling

**Comment by afomi** [comment]
@hackajesse, bump, as I think this may be done.

**Comment by hackajesse** [comment]
gracias, @afomi
