### ISSUE TITLE
Add reminder to clean drain to your calendar

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#10]

**Comment by jeanwalshie** [comment]
i'd like to think about this further. where and when would the user get this prompt to add to calendar? would it be an option in the box that appears once a person adopts a drain, perhaps below the "Abandon this Drain" button? would we enable them to add it to a Gmail, Outlook, Apple... and Yahoo? would love thoughts from @jafowler49 and @jszwedko :) as to how hard this would be to implement.

**Comment by jszwedko** [comment]
Hmm, was the thinking that this would be a calendar feed that would be managed by the city? I could see us having a single calendar feed that people could subscribe to (that way, you could add calendar events in advance of weather events).

**Comment by jeanwalshie** [comment]
i'm closing this because we already email drain adopters in advance of heavy rains and we are currently exploring sending text message reminders as well.
