### ISSUE TITLE
Add storm_use_code to Things table and pass back to frontend

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#100]
I think all that needs to happen is to:

- [ ] Add storm_use_code to schema on Things table
- [ ] Populate storm_use_code from drains data

The `find_closest` method on the thing model already passes back all fields, so once this is done, it should be pretty straightforward to swap in the other icon (which is already designed) when we match MS4 to the storm_use_code per the discussion on #38

**Comment by jasonlally** [comment]
@jszwedko @afomi - this one ends up actually being more important to the launch than I originally understood. Can we huddle on this tomorrow real quick? I think it should be straightforward. I haven't really touched rails migrations/schemas before, so I'd love your help here. 

/cc @hackajesse

**Comment by jeanwalshie** [comment]
Thank you!!!!

Jean Marie Walsh
Communications Manager
San Francisco Public Utilities Commission
525 Golden Gate Ave. 12th Floor
(415) 554-3203
jwalsh@sfwater.org<mailto:jwalsh@sfwater.org>

**Comment by jszwedko** [comment]
@jasonlally sure thing, I'm happy to work on this tomorrow during hack night.
