### ISSUE TITLE
Make location search available to users not logged in

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#103]
Based on some observations by @jeanwalshie users found it difficult and non-obvious to find drains near their work or home because search is currently only made available when logged in. And users first instinct isn't to create an account but to look for adoptable drains.

Given that the call to action to sign in isn't made until a user clicks on an available drain, I think it makes sense to make drain discovery as simple as possible.

Simplest way to implement this quickly is to make the search persist rather than be only available when logged in.

**Comment by jeanwalshie** [comment]
@jasonlally looks like this has been implemented, sort of. the drains now drop down when a user is not logged in, but there is no address search bar.

**Comment by jszwedko** [comment]
I believe the drains have always appeared when not logged in. I think this issue is about adding adding the address search specifically.

**Comment by jeanwalshie** [comment]
yep, i think you're right.

**Comment by jasonlally** [comment]
Yes, we need to expose the search bar to folks that aren't logged in. Before we do that, any possible issues with rate limits on the geocoder if someone sends a bunch of requests? I'm not certain, but the friction on the search may have been done purposefully to limit hitting the geocoder.

**Comment by jszwedko** [comment]
That is a good note -- this may require adding functionality to rate limit end-user requests.

**Comment by jeanwalshie** [comment]
hi again, reviving this because we've gotten more user feedback: "once I signed up and logged in, there was the ability to search by address/neighborhood, but it would still be useful to have this ability BEFORE signing up to see where the drains are located/adoption is needed."

**Comment by jszwedko** [comment]
@jeanwalshie I took a stab at this (in #196) which I've pushed to the staging environment (http://adoptadrainsf-staging.herokuapp.com/) if you could take a look. You'll note that users have to click a button to sign in or register now (the sidebar seemed to busy if I left it underneath the search form). Please let me know what you think!

**Comment by jeanwalshie** [comment]
hi @jszwedko I like it! but now the words "address, location" seem almost like a caption for the video. i wonder if we can remove them. or put them within the search bar, in place of " 1 Dr. Carlton B Goodlet..."?

**Comment by jszwedko** [comment]
Good call, I removed the label and updated the placeholder. Let me know what you think!

**Comment by jeanwalshie** [comment]
@jszwedko i think it works great!

**Comment by jszwedko** [comment]
Promoted to production!

**Comment by jeanwalshie** [comment]
@jszwedko this looks done, eh? i'm gonna close it. thank you!

**Comment by jszwedko** [comment]
Yep! Thank you for cleaning up.
