### ISSUE TITLE
Add DataSF logo

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#106]
Need to add the "logo" for DataSF.

**Comment by jeanwalshie** [comment]
did we decide to replace the CfA logo with DataSF, or add DataSF?

**Comment by jszwedko** [comment]
Do we have the logo for this? I wasn't able to find anything with a quick search.

**Comment by jszwedko** [comment]
cc @jeanwalshie @jasonlally

**Comment by jasonlally** [comment]
I can add it.

**Comment by jeanwalshie** [comment]
@jasonlally @hackajesse a related idea: someone suggested that we include information about how this was developed and how people can do something similar in their own city. the logos go to our agency pages, where one could potentially piece it all together, but there's nothing about this particular app and how it came to be. thoughts?

**Comment by jszwedko** [comment]
Good idea! I think that is out of scope of this issue though, I'll create a separate one to discuss it.

**Comment by jszwedko** [comment]
Bump @jasonlally :)

**Comment by jeanwalshie** [comment]
@jasonlally now would be a good time to add that DataSF logo cuz we're gonna start promoting this app! :)

**Comment by jeanwalshie** [comment]
i see the logo is up. looks like we can close this? @jasonlally

**Comment by jasonlally** [comment]
Yep
