### ISSUE TITLE
Add something indicating we use zenhub to help manage issues

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#110]
I don't know where to put it, maybe just the Readme? But zenhub needs to be installed as a browser extension in order for the boards to be visible. This may help new folks get plugged into where things are.

![boards](https://cloud.githubusercontent.com/assets/534176/12176464/5ef4dd16-b51c-11e5-97c6-d3634a02b51c.PNG)

**Comment by jasonlally** [comment]
Link here: https://www.zenhub.io/

**Comment by jszwedko** [comment]
I would say README under the contributing section. I actually haven't been using zenhub, but I've been meaning to look at it.

Slightly related to #109

**Comment by howdoicomputer** [comment]
For some of my projects I link to a contribution guide that sits in the wiki.

EX: https://github.com/codeforsanjose/codeforsanjose-backend/wiki/Contribution-Guide

**Comment by jszwedko** [comment]
:+1: to adding a contribution guide

**Comment by jeanwalshie** [comment]
revisiting this so that we can move on some of these items, or close them out. 

now that we are trying this "projects" tab, how does that affect this idea of including info about zenhub? @jasonlally @jszwedko @jafowler49

**Comment by jszwedko** [comment]
I'd say that the Projects tab takes the place of what we would have used Zenhub for (and is documented in https://github.com/sfbrigade/adopt-a-drain/wiki/Adopt-a-Drain-SF-Development-and-Deployment-Processes). I'm 👍 on closing this one.

**Comment by jafowler49** [comment]
ditto @jszwedko

**Comment by jeanwalshie** [comment]
another one bites the dust. thanks @jafowler49 and @jszwedko!
