### ISSUE TITLE
Add "alpha" banner to top of site

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#111]
Since we're softly launched but still working, we should maybe add a little banner at the top.

Something like:

This site is in ALPHA: We're just getting started. We'd love to get your feedback or your help with code.

**Comment by jeanwalshie** [comment]
yes, please!

**Comment by jeanwalshie** [comment]
@jasonlally @jszwedko - now would be a good time to add this messaging since we're going to start promoting! (will ease people's minds that the app is not a done deal and there is still room for improvement.)

**Comment by jszwedko** [comment]
:+1:

**Comment by jszwedko** [comment]
Added text encouraging users to leave feedback, please re-open if either of you had something else in mind.
