### ISSUE TITLE
Name your drain

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#12]

**Comment by jbonaguro** [comment]
Love in concept...and may need to think about vetting

**Comment by hackajesse** [comment]
@jasonlally do you have the link to the db of bad words? 



– 
Jesse Biroscak

jesse.biroscak@gmail.com

c. 415.439.3164


[Li] [Tw]

**Comment by hackajesse** [comment]
This seems to be deployed already. @afomi did you modify anything to make this happen?

**Comment by afomi** [comment]
Hi @hackajesse,

In terms of bad-word filters, here are a couple popular libraries. Adopta doesn't seem to have a filter built in. 

* https://github.com/intridea/profanity_filter
* https://github.com/tjackiw/obscenity

The `Thing` object does have a `name` field. For this instance of Adopt-a-drain, the name field was populated with the `Drain_Type` value from the dataset.

**Comment by hackajesse** [comment]
@afomi, 
Name field is nearly certain to be different from `Drain_Type` and it may make the most sense to differentiate in the db. 
This may require:
* changing the database to have a separate `name` column that can be validated against the profanity db
* validation copy

Other stuff you'd suggest?

**Comment by jszwedko** [comment]
A separate field to store the type would probably be useful, but I'd argue that we should do that when needed to drive functionality (and just back populate) than worry about it now.

I feel like profanity filters never really help much (people just work around them if they really want to) -- a solution I think is more effective is to let people "report" bad content and then moderate that way (we can block a given e-mail for repeat offenders). What do you think @hackajesse @afomi ?

**Comment by hackajesse** [comment]
@jszwedko I'm partial to an initial filter given it's the City and they'll want some sort of basic control. That said, you're absolutely right about people going around it. Reporting would be a nice feature, but prob not for the MVP. Creating an issue to capture that feature.

**Comment by jszwedko** [comment]
@hackajesse thanks for the details, I'm :+1: to having the basic filter.

**Comment by jszwedko** [comment]
Closing this given that you can already name your drain when you adopt it. I'll open a new issue for filtering words.
