### ISSUE TITLE
Make slight edits to legend 

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#127]
minor thing: how would folks feel about removing the words "Available" in the legend so it just says "Drains to Sewer" and "Drains to Ocean/Bay"? I feel it looks cleaner/tighter that way and the fact that the drains are available is obvious. 

![image](https://cloud.githubusercontent.com/assets/15933453/12498095/d5fda788-c054-11e5-879a-edab80fe1522.png)

**Comment by jszwedko** [comment]
Agreed! See #128

**Comment by jeanwalshie** [comment]
looks great, thanks! @jasonlally @jszwedko
