### ISSUE TITLE
Switch to HTML e-mails and use current copy

### ISSUE THREAD

**Issue by jszwedko** [sfbrigade/adopt-a-drain#138]
Now that we have more of a need (additional styling and links).

First e-mail: https://docs.google.com/document/d/1ogprm41vY17Wj-rSjOds7UOJDQGtv6t4oiswYEDTtAg/edit

Second e-mail: https://docs.google.com/document/d/1mtugVFh8KFzTUtKCEm0RCdUpsX0enKdAR5aqWrI8fWo/edit

**Comment by jeanwalshie** [comment]
It looks like we are still using the old, outdated copy for the 2nd email (that says "you're a draintastic person!" The correct, current copy is in the links above.

**Comment by jeanwalshie** [comment]
doesn't look like this has been done. also, i updated the copy for the **1st email **with a safety video, as requested by SFPUC management. hoping the most recent copy for both emails can be used!

**Comment by jszwedko** [comment]
:+1: this still needs to be addressed. I plan on spending some of Code for SF Hack Night tomorrow on this.

**Comment by jszwedko** [comment]
I adjusted the copy in the Google doc slightly:

> P.S. Did you download the 311 app? Here’s the link!

to:

> P.S. Did you download the 311 app?

Where "the 311 app" is the link to the app. This is more in line with accessibility standards which say to shy away from using links with ambiguous text like "link" or "click here". See https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/G91 for more.

**Comment by jeanwalshie** [comment]
@jszwedko I tried to find you last night at hack night, but you disappeared! Thanks so much for working on this.

the 2nd email is still using the **old** copy. 1st email (and HTML) looks good.

**Comment by jszwedko** [comment]
Oh no! I must have been downstairs.

Is https://docs.google.com/document/d/1mtugVFh8KFzTUtKCEm0RCdUpsX0enKdAR5aqWrI8fWo/edit the correct document for the second e-mail? Note that I haven't merged the changes yet, so they aren't live (wasn't sure if you were looking at the pull request HTML directly, or at the e-mails the app is currently sending).

**Comment by jszwedko** [comment]
I merged #161 so these changes'll be live now -- please let me know if they need any additional adjustments!

**Comment by jszwedko** [comment]
Reopening so you can close after verification @jeanwalshie .

**Comment by jeanwalshie** [comment]
Thanks, @jszwedko!!! looks terrific. The only thing left is the subject line for email #2 - it's still the old one ("draintastic person" haha). Should be "Thanks for adopting another drain, [name]!" Once that's done we can close this one out!

**Comment by jszwedko** [comment]
Oops! MIssed the subject change -- I'll update now.

**Comment by jszwedko** [comment]
The subject should be updated.

**Comment by jeanwalshie** [comment]
awesome, thanks!!
