### ISSUE TITLE
Get rid of "Click" (A11y)

### ISSUE THREAD

**Issue by j6design** [sfbrigade/adopt-a-drain#142]
Change "Click to learn what this means." to "Learn more about adopting a Drain" and make it the link.

**Comment by jeanwalshie** [comment]
I like that idea @j6design. But with the word "drain" uncapitalized. :)

**Comment by j6design** [comment]
copy/paste got me :)

**Comment by jeanwalshie** [comment]
hey, this is done! thanks @jszwedko . closing.
