### ISSUE TITLE
After adopting, add link/instructions to what to do

### ISSUE THREAD

**Issue by j6design** [sfbrigade/adopt-a-drain#148]

**Comment by jeanwalshie** [comment]
@j6design -- after adopting a drain the user receives an email with instructions. is that what you mean?

**Comment by j6design** [comment]
@jeanwalshie -- mainly an on-screen notification -- like "...check your email for detail instructions and use the map/form to explore a drain..."

**Comment by jeanwalshie** [comment]
closing this out. with the on screen instructions and auto email, i think it's clear.
