### ISSUE TITLE
When updating profile - error when no password entered

### ISSUE THREAD

**Issue by j6design** [sfbrigade/adopt-a-drain#149]

**Comment by jszwedko** [comment]
@j6design I think it is common to require the password when modifying a profile on a given site to avoid the possibility of someone making malicious edits on your behalf (particularly changing the e-mail address). I do see that there is an issue with processing of form errors where it redirects you though, I will address that.

**Comment by jszwedko** [comment]
@j6design submitted PR (#152) to address the form submission issue -- let me know what you think about the password requirement -- I'd personally like to keep it, at the very least when the user is changing their e-mail address.

**Comment by jszwedko** [comment]
Closing after in person discussion about the requirement of a password when changing account information.
