### ISSUE TITLE
Yikes! Can't adopt a drain in Explorer

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#155]
when you click on a drain, nothing happens.

**Comment by jszwedko** [comment]
Hi @jeanwalshie! Can you provide more information including the version of Windows and the version of Internet Explorer where you saw this?

**Comment by jeanwalshie** [comment]
sorry, @jswedko, of course. this was with IE Version 9 and Windows 7 Enterprise.

**Comment by jszwedko** [comment]
Thanks for the additional detail! Should help me reproduce.

**Comment by jszwedko** [comment]
Didn't mean to close this.

Apologies for the delay, was on vacation, but this should be addressed. Let me know if you still see this bug! Please close this issue if you do not.

**Comment by jeanwalshie** [comment]
thanks @jszwedko ! it's fixed!
