### ISSUE TITLE
idea for spreading the word

### ISSUE THREAD

**Issue by thfield** [sfbrigade/adopt-a-drain#156]
When I went to college, the student groups would "chalk the quad" to get the word out about events, groups to join, etc.  Adopt-a-drain could use chalk at the drains themselves to raise awareness at the source (pun semi intended). Or ideally, a more semi-permanent method of marking the street.  
SF has a thriving street art culture, there could be a way to leverage sticker- or stencil- artists in a way that would be agreeable to the city, ie non-permanent.

**Comment by jszwedko** [comment]
Hi @thfield apologies for the delay, was on vacation last week -- I think this is a pretty cool idea.

CCing @jeanwalshie

**Comment by jeanwalshie** [comment]
what a great idea! "Adopt me!" i'll add this idea into the adopt-a-drain promo plan i'm creating and we can see if we can make it happen. thanks @thfield

**Comment by thfield** [comment]
glad to help!

**Comment by jszwedko** [comment]
:+1: I'll close this since @jeanwalshie has added it for consideration to the promo plan. Thanks again @thfield
