### ISSUE TITLE
Ideas for Increasing Adoption

### ISSUE THREAD

**Issue by judecalvillo** [sfbrigade/adopt-a-drain#157]
Here are a few more ideas for increasing adoption, and they're mostly in the form of cost-effective marketing programs.

* **Demand-based programs:**
  + Place and maintain prominent, persuasive buttons/links to Adopt-a-Drain on all city-owned web pages that rank highly for search terms like "report a flooded drain" (e.g. http://www.sf311.org/index.aspx?page=127, http://www.sfwater.org/index.aspx?page=130).
  + Present prominent, persuasive buttons/links to Adopt-a-Drain in the 311 app, before and after someone has completed a flooded drain report. Actually, in particular, one can envision integrating positive -and negative- social motivators into the before-reporting instance (e.g. rating, thanking, and/or reminding nearby adopters).
* **Discovery-based programs (in addition to traditional ads and PR):**
  + Direct marketing (e.g. mailers, email, or flyers) to businesses near chronically flooded drains, as impacted business owners might be motivated to either adopt these drains themselves or at least share promotional materials with their customers.
  + Promotional partnership with landlord associations like the [SFAA](http://www.sfaa.org/), whereby they post or drop-mail flyers, as many of SF's landlords and property management companies are likely interested in maintaining positive perceptions around their neighborhoods. Plus, one can see where Adopt-a-Drain could cut some of their maintenance costs (e.g. keeping lobby assets drier). 
  + Promotional partnership with neighborhood associations and coalitions, like the [Coalition for SF Neighborhoods](http://www.csfn.net/about-us.html), whereby they regular promote AAD and a neighborhood's adopters via their newsletters/communications.

And finally, since mechanical "growth hacking" is largely a function of natural growth, at least early on, I humbly propose that focusing on developing the aforementioned programs should do more for traction than building out growth hacking mechanics at this time. Still, if the team has the resources, why not do both? 

Keep up the great work! Looking forward to hearing of SF becoming the "drain adoption capital of the world." ;)

-_Jude_

**Comment by jeanwalshie** [comment]
great ideas, @judecalvillo! i have a promo plan started and i'll add these ideas to it and circulate. thank you!

**Comment by judecalvillo** [comment]
:) NP. Have a great day, @jeanwalshie. Ttys.
