### ISSUE TITLE
In the Admin area, is there an easy way to see which drains a person has adopted?

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#158]
I see latitude and longitude. And a field called ID [Things] and City [Things] - but i'm not sure what these mean.

**Comment by jszwedko** [comment]
@jeanwalshie if you are viewing a person, you can see the drains they've adopted listed at the bottom. The `City` field maps to the `PUC_Maximo_Asset_ID` from the original data set (minus the `N-` to make it numeric).

**Comment by jeanwalshie** [comment]
thanks @jszwedko. i should have been more clear: i'm wanting to be able to see both the total number of drains that have been adopted as well as where they have been adopted, ie on the map.

**Comment by jszwedko** [comment]
Ah, gotcha, we can talk more about what that looks like to integrate into the site itself, but a simple workaround for now would be to export the adopted drains and load them into Excel (which has the ability to plot ion a map).

**Comment by jeanwalshie** [comment]
hey @jszwedko, following up on this. i'm not sure how to identify/export the adopted drains. what field am i looking for? also, this may be temporary, but i'm getting a message "We're sorry, but something went wrong." when trying to export drains...

**Comment by jszwedko** [comment]
@jeanwalshie apologies for the delay -- lost track of this issue.

I can't remember if we talked about this before or after you left this comment (so apologies if this is redundant), but you can find drains that have been adopted via:

https://adoptadrain.sfwater.org/admin/thing?model_name=thing&utf8=%E2%9C%93&f%5Buser%5D%5B08380%5D%5Bo%5D=_not_null&f%5Buser%5D%5B08380%5D%5Bv%5D=&query=

(note the filter I'm applying is that `User is present`)

Once you have the desired filters applied, you can click the "Export found things" button.

**Comment by jszwedko** [comment]
It looks like Heroku times out the request if you try to export all of the drains at once (since it caps the request time at 30 seconds), but you can easily export only the adopted drains.

I can look and see if there are any optimizations we can make to make it possible to export them all at once.

**Comment by jeanwalshie** [comment]
got it! thanks. i was able to export only the adopted drains (269 so far!) and map them. FYI, they're pretty spread out around the city, which is cool.
