### ISSUE TITLE
Work with CfSF Coordinator on hosting expenses

### ISSUE THREAD

**Issue by afomi** [sfbrigade/adopt-a-drain#16]
Hi @hackajesse, this project requires 21,000+ records to be stored. Heroku's free tier maxes out at 10,000. 

Is there a SF Brigade account that could host this and manage the payment? Or any other alternative :smile:

**Comment by afomi** [comment]
A Heroku account was created for `sfbrigade@gmail.com`, and this Adopt-a-drain instance is now owned by that account.  My CC info is currently attached to the account, so I'll need to work with @hackajesse, or another CfSF member to update that with the appropriate billing info.

**Comment by hackajesse** [comment]
@afomi will you be at hacknight? We can take care of it on Wednesday. If not, slack me to coordinate.

**Comment by afomi** [comment]
ya - happy to chat this Wednesday

**Comment by jszwedko** [comment]
@afomi assigning you since it looks like you are owning this, but let me know if not! Happy to help or take over.

**Comment by jszwedko** [comment]
@hackajesse @jasonlally @afomi any update on how we should proceed with paying for the service?

**Comment by jszwedko** [comment]
Bump @jasonlally @hackajesse

**Comment by jasonlally** [comment]
I can take over payment as we wait...I have access to the application, can I just change over billing there?

**Comment by jasonlally** [comment]
I think I need to have different permissions to pay for the application. @jszwedko do we need to transfer ownership?

**Comment by afomi** [comment]
yes ownership will need to be transferred. to which email?

**Comment by jasonlally** [comment]
@afomi, @jszwedko successfully transferred ownership to me. Billing should now come out of my account.

Thanks @jszwedko 

Closing this.
