### ISSUE TITLE
Create survey to capture info about drains cleaned, gather feedback, etc. 

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#160]
We can model it on Oakland's, but make ours a little shorter/simpler: https://docs.google.com/forms/d/1UphXhPsn0BtVsquilDYnZDfcirO7xvt1sUnh-OoCj28/viewform?c=0&w=1

The idea would be to include the survey link in the email we send to adopters. 

In the future it would be nice for users to be able to log their work from the app, but this doesn't exist yet. referencing: https://github.com/sfbrigade/adopt-a-drain/issues/45

**Comment by jszwedko** [comment]
Good idea :+1:

**Comment by jeanwalshie** [comment]
Here's a draft of a survey: https://www.surveymonkey.com/r/adoptadrainsf

**Comment by jeanwalshie** [comment]
I'm going to close this one. I created a survey and will send to adopters and share the results with anyone who's interested!
