### ISSUE TITLE
Error in password reset language

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#162]
If a user makes a mistake resetting their password they get this message: "Password reset token is is invalid" (both makes no sense and has two is's). 

Maybe it can say instead, "Password reset is invalid." 

This came up for me when I tried to reset my password using an earlier password reset link (I requested a new password twice in a row and got two emails.) 

Hope this makes sense!

**Comment by jszwedko** [comment]
Good catch, I'll update to say `Password reset link is invalid`.

**Comment by jszwedko** [comment]
Updated text!
