### ISSUE TITLE
Box doesn't disappear when X is clicked

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#163]
In the blue box there is an X, which indicates that the box will go away when the X is clicked, but nothing happens. 

![image](https://cloud.githubusercontent.com/assets/15933453/14035108/a2548504-f1e7-11e5-9603-956ddd6e2166.png)

Not a huge deal, but maybe can be fixed?

**Comment by jszwedko** [comment]
Good catch, just addressed this, thanks @jeanwalshie !
