### ISSUE TITLE
What unique id (from the City) do we store in Adopta?

### ISSUE THREAD

**Issue by afomi** [sfbrigade/adopt-a-drain#17]
Adopta's `Thing`s table has a `city_id` field, which I'm assuming is to store an external identifier. 2 fields looked like candidates, and I have hunch which one, but wanted to clarify.

From a sample record:

`"DPW_Node_ID":"22337" `
or
`"PUC_Maximo_Asset_ID":"N-36453"`

cc @jasonlally, @hackajesse

**Comment by jasonlally** [comment]
Use PUC_Maximo_Asset_ID

**Comment by afomi** [comment]
okay. I used `DPW_Node_ID` on initial import. I'll update the records

**Comment by afomi** [comment]
The records have been updated in Production. 

`PUC_Maximo_Asset_id`s are now the values for `Thing.city_id`'s.

**Comment by afomi** [comment]
Thanks for clarifying @jasonlally!

Closing this issue.
