### ISSUE TITLE
Conduct user testing

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#170]
hey hey, how can we get folks to test out this app? I've been peddling it around the SFPUC, but would be good to get more eyeballs on it.

**Comment by jszwedko** [comment]
Good question, maybe @hackajesse has some ideas? :smile:

**Comment by jeanwalshie** [comment]
i'm gonna close this because the app is live and we are getting feedback via email and a survey we sent out.
