### ISSUE TITLE
Automatically refresh list of drains

### ISSUE THREAD

**Issue by jszwedko** [sfbrigade/adopt-a-drain#173]
Currently the list of drains in Adopt-A-Drain is static. We would like to be able to refresh this either via:
- Automatically repolling the API (preferred)
- Create an admin page where an admin can trigger a refresh

See https://github.com/sfbrigade/adopt-a-drain/blob/production/lib/tasks/data.rake for how it currently loads the data. This is a rake task that can be run to update the data, but we'd like for a non-technical user to also be able to do this (or for it to happen automatically).

**Comment by jeanwalshie** [comment]
that's a great idea @jszwedko

**Comment by jeanwalshie** [comment]
@jszwedko @jasonlally I wonder if we can pull the drain data into the app again, as we have new drains that users told us about (in the street but not previously in our records) and would like to reflect that in the app. :)

**Comment by jafowler49** [comment]
@jszwedko @jasonlally  Hi Jesse! I'm James from SFDT. I'm working on the Adopt a Drain Project... Hi Jason, we met in the meeting here at DT.

@jasonlally I believe you oversee the actual drain data aggregation and uploading to DataSF?  

I've been working on this Issue, but I have a question in regards to how we ensure that data is accurate. 

For example, currently lat/lng drain locations are OK, but in the past I've come across drain data whose lat/lng were incorrect. Something must've went wrong in the processing of drain data, which caused lat/lng locations to be completely out of bounds of San Francisco.

Is this something we should assume will be correct on the data aggregation/archiving side, or should we have validation checks on the application side. Or both.

Thanks!

**Comment by chaunceygraves** [comment]
Hi James,
Welcome to Adopt a Drain. I’m data custodian for sewer engineering at Public Works, but at this point just a lurker on the GitHub part of this. Janine Heiser at DT with SFGIS group set up the auto load of drain data from us at Public Works to dataSF, you might want to talk to her…2nd floor SVNess I think?  However, our database view calculates the lat/long and issues with that may be on our side? Can you give us any specific record IDs to look at? Identify the issue-records by PUC_Maximo_Asset_ID from here: https://data.sfgov.org/City-Infrastructure/Stormwater-inlets-drains-and-catch-basins/jtgq-b7c5

Thanks

John Seagrave  | Engineering Associate
Hydraulic Engineering  |  Public Works  |  City and County of San Francisco
1680 Mission St |  San Francisco, CA 94103   |  (415) 554-8305 |  john.seagrave@sfdpw.org<mailto:john.seagrave@sfdpw.org>

**Comment by jafowler49** [comment]
@chaunceygraves Thanks, for the quick response. The current data looks ok, but when I downloaded data back in December it was incorrect. 

I've attached a copy of the data from back in December as an Excel attachment. You can see that the lat/lngs are incorrect.

Thanks for looking in to it

[Stormwater_inlets__drains_and_catch_basins-dec.xlsx](https://github.com/sfbrigade/adopt-a-drain/files/767534/Stormwater_inlets__drains_and_catch_basins-dec.xlsx)

**Comment by jasonlally** [comment]
@jafowler49 - the issue was fixed back in December. Lat/long got inverted during automation so you must have downloaded during the window where there was a data issue.

Thanks for checking in on this though.

**Comment by jasonlally** [comment]
@jafowler49 - I assume you know this, but just in case there's been some effort in this direction that you may be able to leverage. There's an open WIP pull request here #217 and earlier #198 

@jszwedko and @squidarth were contributing.

**Comment by jafowler49** [comment]
thanks @jasonlally . I actually didn't notice those. Good thing you told me about it because it could be a problem editing the same files

@jszwedko It looks like those two branches can be merged by fixing one file. I think they are spacing issues. If you're doing pull request merging can you merge these branches so all commits can be on prod.

Thanks!

**Comment by jszwedko** [comment]
:+1: I'm hoping to push forward #217 this weekend.

**Comment by jafowler49** [comment]
Looks like this is being taking care of in the other pull requests.... All we need is a Heroku cron job to run the job continuously

**Comment by jszwedko** [comment]
Made one more tweak to prepend `N-` to the City IDs for clarity and configured the task to run daily at midnight. Will check on this tomorrow morning to make sure it ran successfully.

**Comment by chaunceygraves** [comment]
Hi Jessie,
The “SFPUC_Maximo_Asset_ID” should already have an “N-“ on the front: make sure you’re not prepending to DPW_Node_ID which does not have an N and is a different number, see below. Call if you have questions.

thanks

[cid:image001.png@01D2BD0C.7B2FE7C0]

John Seagrave  | Engineering Associate
Hydraulic Engineering  |  Public Works  |  City and County of San Francisco
1680 Mission St |  San Francisco, CA 94103   |  (415) 554-8305 |  john.seagrave@sfdpw.org<mailto:john.seagrave@sfdpw.org>

**Comment by jszwedko** [comment]
Thanks for clarifying @chaunceygraves!

In this case, this is the field mapped from `PUC_Maximo_Asset_ID` as `city_id`. We strip the `N-` when importing as the column we are storing in is an integer so I'm prepending again in the output to make it clear that this is the Maximo asset ID.

Initially we'd kept the `city_id` as an integer for compatibility with the upstream Adopt-a-Hydrant project, but I think we've veered off enough that I'd be open to changing the column to a `varchar` and actually keeping the `N-` during import to avoid the need to strip and reappend.

**Comment by jeanwalshie** [comment]
this is running, right? can we close this issue? @chaunceygraves

**Comment by jszwedko** [comment]
This has been live for long enough that I'm comfortable closing it out. Thanks to everyone that helped make this happen!
