### ISSUE TITLE
positive feedback! 

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#174]
This is not an "issue" per se, just some positive feedback I wanted to share! :) @hackajesse @jszwedko @jasonlally 

Dear SF Water Folks.

My family of four have typically cleaned the two drains in our neighborhood (which I signed up for tonight) at our corner for the past 25 years. I am glad you began this program as it involves people in our community and helps me teach my sons a sense of civic pride and duty. My father is a retired civil engineer and one of his tasks was to design road drains. My siblings and I grew up understanding the importance of cleaning drains. I have taught my sons this lesson.

I hope this program takes off.

**Comment by jszwedko** [comment]
Very cool, thank you for sharing @jeanwalshie !

**Comment by jeanwalshie** [comment]
just wanted to share that so far **212 people** have adopted **330 drains**. woo hoo!!!

**Comment by jszwedko** [comment]
Awesome! :trumpet:

**Comment by jeanwalshie** [comment]
update: 291 users, 458 drains adopted!

**Comment by jszwedko** [comment]
Nice! Let's keep it going.
