### ISSUE TITLE
Enable orgs to import a logo to appear by their adopted drain

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#176]
Just an idea, but this would be modeled on the "adopt a highway" program where signs are placed along the highway, giving credit to the org who takes care of the highway. 

The idea would be to allow users to upload their company/organization's logo to appear when someone clicks on the drain.

**Comment by judecalvillo** [comment]
:+1: Great idea!

**Comment by jeanwalshie** [comment]
i'm gonna close this. orgs can already name their drain with their business or other entity, and we don't want the site cluttered up with logos, on second thought...
