### ISSUE TITLE
Enable Admins to add other Admins

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#177]
and see who the other Admins are.

**Comment by jszwedko** [comment]
@jeanwalshie you can actually already do this in the `Admin` section.

You should be able to see them at https://adoptadrain.sfwater.org/admin/user?model_name=user&utf8=%E2%9C%93&f%5Badmin%5D%5B26241%5D%5Bv%5D=true&query= but more generally you can filter users by many different filters on that page (the like has them filtered by `Admin=true`.

**Comment by jszwedko** [comment]
To add a new admin, find their user in the users list (or have them register first if they haven't), and then click

![screen shot 2016-06-15 at 10 59 12 am](https://cloud.githubusercontent.com/assets/316880/16084867/465a654c-32e8-11e6-84d5-d72d1a690914.png)

**Comment by jeanwalshie** [comment]
perfect, got it! sorry, i should have been able to figure this out myself. still familiarizing myself with the admin area. thank you, @jszwedko!!!
