### ISSUE TITLE
change copy on email people can send when they adopt a drain 

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#180]
from: "The rains of El Niño are coming! So I just adopted one of San Francisco's 25,000+ storm drains and pledged to help keep it clear of leaves and debris this rainy season. You too can lend a hand and help the City avoid flooding at https://adoptadrain.sfwater.org/.

to: "I just adopted one of San Francisco's 25,000+ storm drains and pledged to help keep it clear of leaves and debris. You, too, can Adopt a Drain and help the City avoid flooding at https://adoptadrain.sfwater.org/.

**Comment by jszwedko** [comment]
Good call, thanks for the new copy! Added in #185
