### ISSUE TITLE
Have Facebook and Twitter links open in a new window

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#181]
When someone adopts a drain a pop up window appears with icons that link to Facebook and Twitter. Would be better if they opened in a new window instead of driving users away from the page. 

Same is true for the logos on the homepage: should open in an new window.

**Comment by jszwedko** [comment]
Good idea! Addressed in #184

**Comment by jeanwalshie** [comment]
hurray!
