### ISSUE TITLE
Fix broken link in first email

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#182]
The link to Adopt-a-Street should be: http://www.sfpublicworks.org/get_involved/adopt-street-program

**Comment by jszwedko** [comment]
Thanks for the new link! Updated the e-mail (though it was the second adoption email, not the first, unless I'm missing something).

**Comment by jeanwalshie** [comment]
sorry, you're right! 2nd email. thank you!!!
