### ISSUE TITLE
Readme: "Create a topic branch" link broken

### ISSUE THREAD

**Issue by mnorelli** [sfbrigade/adopt-a-drain#189]
Under the section _Submitting a pull request_, the link to "Create a topic branch" goes to:

http://learn.github.com/p/branching.html

This is what the Wayback Machine says it used to look like:

https://web.archive.org/web/20120315041836/http://learn.github.com/p/branching.html

The link in the readme is broken and doesn't resolve to anything useful.  Three possible choices for replacements are:

(A) https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/
(B) https://guides.github.com/introduction/flow/
(C) https://github.github.com/on-demand/intro-to-github/04/

or even things more animated, like http://learngitbranching.js.org/?demo

Which one makes the best replacement may depend on the intended audience.  (B) is the most interesting and shortest, but requires a couple clicks and doesn't give syntax.  (A) is a bit more specific but short, and leads to (A).  (C) is a part of an online class, and might be closest in spirit to the original link content.  It has a video.  But it leads people on to the next lesson in the class and might be confusing for that reason.

I vote (B) but interested in any feedback before submitting a pull request.

**Comment by jszwedko** [comment]
Awesome, thanks for opening this @mnorelli. I also cast my vote for (B) -- it feels the closest in spirit to the original link.
