### ISSUE TITLE
Post promo video (and logo question)

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#192]
We are finalizing some short 30-second videos to promote the adopt a drain program and would like to post or link to the video/s on the site.

The question is where and how? Post an actual video, maybe at the bottom by the logos, or a link to a YouTube page, possibly in the Learn More section? 

I'm also wondering if we should be including the Code for America logo - they didn't actually work on or support this particular project, aside from providing space for hack nights, and support for the original app. @jasonlally what do you think? We refer to them in the Learn More section.

**Comment by jotasprout** [comment]
I would recommend embedding YouTube videos. I think it's the easiest and most reliable. If you have some text stating, "We'd like to thank CfA for their space," etc. near the logo, I think it's perfectly appropriate and cool.

**Comment by jszwedko** [comment]
@jeanwalshie awesome! Maybe we could embed one of them in the "Learn more" section and link to a Youtube playlist of the rest?

**Comment by jeanwalshie** [comment]
@jszwedko @jotasprout ok, here are the videos! Maybe we should embed the 15 or 30 second one. would it be best in the "Learn More" section or right on the homepage in the bottom by the logos?  I think we can get rid of Code for America and give a shoutout to them in the Learn more section. 

15 sec: https://youtu.be/OMykGwBc1eI

30 sec: https://youtu.be/Z1Vjrx3IAH0

Profile Mark: https://youtu.be/I8mlmaA63Zc 

Benefits: https://youtu.be/k_9PHbkbh34

Storm Stories: https://youtu.be/J3VvLshNE4Y

**Comment by jotasprout** [comment]
@jeanwalshie @jszwedko I like the idea of embedding one and linking to the playlist. Want me to take this one? I'd like to.

**Comment by jeanwalshie** [comment]
Yes pls on the embed! But hold off on the playlist- currently the vids are separate. I'm working on making a playlist. Thank you!!

Sent from my iPhone

On Oct 15, 2016, at 10:00 AM, Jota Sprout <notifications@github.com<mailto:notifications@github.com>> wrote:


@jeanwalshie<https://github.com/jeanwalshie> @jszwedko<https://github.com/jszwedko> I like the idea of embedding one and linking to the playlist. Want me to take this one? I'd like to.

**Comment by jeanwalshie** [comment]
@jotasprout @jszwedko here's the link to the youtube playlist: https://www.youtube.com/playlist?list=PLi3CgGqFmQsWOflGLenuFhG13Gc_SjgpG

the final MP4 files are here (for the embed): https://www.dropbox.com/sh/xr6wxk0xvnax5bj/AADm_2Wz289WF1fHBJGshT6Aa?dl=0

**Comment by jotasprout** [comment]
I thought you wanted it embedded it using code from YouTube like so: 
![embed](https://cloud.githubusercontent.com/assets/12866150/19462452/bfa994d4-94ba-11e6-8ca2-d08d2c8d610d.png)

**Comment by jeanwalshie** [comment]
Sorry, yes, that works too!!

Sent from my iPhone

On Oct 17, 2016, at 7:41 PM, Jota Sprout <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought you wanted it embedded it using code from YouTube like so:
[embed]<https://cloud.githubusercontent.com/assets/12866150/19462452/bfa994d4-94ba-11e6-8ca2-d08d2c8d610d.png>

**Comment by jotasprout** [comment]
Where might a high-maintenance contributor find this "Learn More" bit?

**Comment by jeanwalshie** [comment]
haha -- it's on the site on the bottom left corner.

**Comment by jeanwalshie** [comment]
Oh, haha! That I can’t help you with ☺

Jean Marie Walsh
Communications Manager
San Francisco Public Utilities Commission
525 Golden Gate Ave. 12th Floor
(415) 554-3203
jwalsh@sfwater.org<mailto:jwalsh@sfwater.org>

**Comment by jszwedko** [comment]
Awesome, @jotasprout, thank you for offering to jump in!

I think I like @jeanwalshie's idea of embedding one of the videos (I'd say the 30s one), at the bottom of the sidebar (app/views/main/index.html.haml); and embedding the playlist in the modal that appears when you click "Learn more" (app/views/sidebar/_background.html.haml).

Let me know if this helps!

**Comment by jotasprout** [comment]
Thank you all! Today's rockstar is ... @jszwedko

**Comment by jotasprout** [comment]
Finally have a moment (a few, actually), so working on it now.

**Comment by jotasprout** [comment]
Where, exactly, at the bottom of the sidebar do you want it? Above or below the logos?

**Comment by jotasprout** [comment]
I don't think I get this haml business and might not be the right person for this. I thought this was simple HTML and, obviously, require hand-holding for this simple task.

**Comment by jszwedko** [comment]
@jotasprout no worries, I'll be around today if you want to talk in realtime (I'll hang out in Gitter: https://gitter.im/sfbrigade/adopt-a-drain). HAML isn't my favorite, but luckily isn't too complex -- take a look at http://haml.info/tutorial.html for an introduction.

I think putting the video towards the bottom of the sidebar makes the most sense, but feel free to try it in several places and submit a PR for what you think looks best.

**Comment by jszwedko** [comment]
Hi @jotasprout,

Apologies for snaking this from under you, but we wanted to get the video up in advance of some press this weekend. You can look at https://github.com/sfbrigade/adopt-a-drain/commit/c39d24d729965dd5e1e8807ac11fa7bfc2a6ef50 to see how I did it though and please feel free to contribute to any of the other issues!

**Comment by jotasprout** [comment]
No apologies necessary. I'll definitely come back and take a look--thanks for that.
