### ISSUE TITLE
Tell users upfront what is needed for their password

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#193]
people hate having to create passwords. what if we said, "Choose an easy password" or "Choose a password (any 4-6 characters)" or something that helps them get over the password barrier.  just a thought.

**Comment by jszwedko** [comment]
In lieu of this, I think we could add the ability to login via Facebook, Twitter, or Google to help reduce friction.

**Comment by jeanwalshie** [comment]
I like that but I wonder if ppl would be worried about privacy and the app posting on their behalf. We should ask users!

**Comment by jeanwalshie** [comment]
i'm going to close this, since the password barrier doesn't seem to be too much of an issue with 1000+ drain adopters! :)
