### ISSUE TITLE
Adopt a Drain Launch Event this Saturday 10/29!

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#195]
hey all,

we are LAUNCHING this thing. Below is an email we sent to the 300+ San Franciscans who have adopted drains using the Adopt a Drain web app, developed right here, by YOU.

The event is this Saturday, 10/29, 10am-12pm at the Southeast Treatment Plant, 750 Phelps.
# We hope you can make it! Please RSVP: https://www.eventbrite.com/e/adopt-a-drain-volunteer-launch-event-tickets-28775535401 

Dearest Drain Adopter,

As of today, nearly 500 drains have been adopted all across San Francisco – and we’re just getting started. THANK YOU!

We are thrilled to invite you to our first-ever Adopt a Drain Launch Event on Saturday, October 29, 2016.

At this family-friendly event, you’ll have the opportunity to: 
• Pick up your free Adopt a Drain supplies and safety vest. That’s right; we have rakes, brooms, gloves, and more! (Supplies are limited, so be sure to register.)
• Get a drain clearing safety demo by the pros. Demos at 10:45 a.m. and 11:45 a.m.
• Take a mini-tour of the wastewater treatment plant. Tours at 10:15 a.m. and 11:15 a.m.
• Learn more about the San Francisco sewer system.
• Interact with project partners, city staff, and your fellow drain adopters, including our video stars! bit.ly/Adopt-A-Drain_playlist.
• Enjoy refreshments, children’s activities, and more. You don’t want to miss it!

WHEN: Saturday, October 29, 2016, 10 a.m. -12 p.m.
WHERE: Southeast Treatment Plant (750 Phelps Street near Third and Evans St. in the Bayview District)

Please R.S.V.P. This event is limited to Adopt a Drain volunteers and their families.

Again, thank you for helping to make our city a better place, protect the environment, and minimize flooding.

We look forward to seeing you!

https://www.eventbrite.com/e/adopt-a-drain-volunteer-launch-event-tickets-28775535401

**Comment by jszwedko** [comment]
:tada: :100:

**Comment by jszwedko** [comment]
Closing this since the event has passed, but it went great!
