### ISSUE TITLE
Add a ticker to site with current # of drains adopted

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#197]
Wouldn't that be cool??

**Comment by jszwedko** [comment]
:+1: I like this idea.

**Comment by jeanwalshie** [comment]
i got another inquiry from Vancouver today (in addition to other inquiries from media and others) about the current # of drains adopted. Just wanting to make sure this doesn't drop off the radar! :)

**Comment by jszwedko** [comment]
@jeanwalshie took a stab at this in #216 which ended up with something that looks like:

![2017-01-08-220032_548x612_scrot](https://cloud.githubusercontent.com/assets/316880/21756407/0fbb08fc-d5ef-11e6-97b4-cd6ddb817342.png)

What do you think?

**Comment by jeanwalshie** [comment]
cool! you got it to work!? amazing, @jszwedko!

the way it displays it almost looks like the drains have been adopted by that person. or maybe that's because the sample number only 3 vs. 1112. 

i would suggest:
- moving it up higher, maybe even just below the green logo. 
- can it say **TOTAL DRAINS ADOPTED**: 
- and maybe in smaller font last updated... (?) This would be to show that it's current/real time info.

**Comment by jszwedko** [comment]
@jeanwalshie :+1: thank you for the feedback! What do you think of something like:

![2017-01-12-205716_766x749_scrot](https://cloud.githubusercontent.com/assets/316880/21918774/c072d31a-d909-11e6-9831-24ffb3721782.png)

**Comment by jeanwalshie** [comment]
i like it! what do you think about having it say "Total Drains Adopted in SF:"? I added "in SF" to make it clear that it's a total number, vs. a number adopted by the user. BUT this confusion will go away when the number is 1250 vs. 3 :)

**Comment by jszwedko** [comment]
Works for me! How about:

> X drains adopted in SF

to make it a bit shorter.

**Comment by jszwedko** [comment]
Merged this in, let me know what you think @jeanwalshie !
