### ISSUE TITLE
Replace existing Adopt a Drain introductory email text. (Posted on behalf of SFPUC)

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#199]
(Posted on behalf of SFPUC)
- [x] Replace the entire introductory email text with the text below.
- [ ] Change font on entire page to Calibri. 
- [x] Change the title to 14 point bold.
- [x] Change the heading to 13 point bold.
- [x] Change the body to 12 point normal.

-----
You just adopted one of San Francisco's 25,000 catch basins or storm drains. Congratulations and thank you for pledging to keep your drain free of leaves and debris. You are joining your neighbors in helping to protect the environment, manage storm water, and minimize flooding. 

### How to Care For Your Adopted Drain 
- If possible, clear the drain before it starts raining. 
- Put leaves and other natural material in the green compost bin. 
- Put trash in the black garbage bin. 
- Clear about 10 feet on both sides of the drain. 
- Medical waste or needles? Construction debris? Toxic materials? **[Report it to the City’s Customer Service Center, 311 on the web (or dial 3-1-1)](http://www.sf311.org/index.aspx?page=127).**

### Drain Cleaning Safety Tips 
- Never try to lift the drain grate. 
- Clear from the sidewalk, not the street. 
- Wear reflective clothing so vehicles can see you. 
- Always wear gloves and be careful of sharp objects! 
- Use a rake, broom, or shovel - not your hands. 

_Remember, the City and County of San Francisco won’t be held responsible for anything that happens to you or others in service of maintaining your drain. Please be careful!_

### Free Tools and Training 
We invite drain adopters to periodic events during the rainy season where they can receive drain cleaning trainings and free tools and supplies. Please keep an eye on your email for notification of these events. You will also receive periodic email reminders from the SFPUC to clear your drains when rain is expected.

### Spread the Word! 
Excited about the Adopt a Drain program? Want to encourage your coworkers, friends and neighbors to participate? Utilize social media to spread the word.  	 	  

Remember to tag us [@SFWater](https://twitter.com/sfwater?lang=en) and to use the following hashtags: [#DrainHero](https://twitter.com/hashtag/drainhero), [#AdoptADrain](https://twitter.com/hashtag/adoptadrain), and [#SFSewer](https://twitter.com/hashtag/sfsewer).
Thanks again, [Name], for adopting a drain in San Francisco. When each of us helps out a little, it makes a big difference! 

Sincerely, 
Your friends at the San Francisco Public Utilities Commission 
415-554-3289 
[info@sfwater.org ](mailto:info@sfwater.org)

PS, Check out these [short videos](https://www.youtube.com/playlist?list=PLi3CgGqFmQsWOflGLenuFhG13Gc_SjgpG) starring your fellow drain heroes.

-----

- [ ] Insert the following images below "Utilize social media to spread the word." and above "Remember to tag us..."
![image](https://cloud.githubusercontent.com/assets/23368836/20506354/479a3d7c-b008-11e6-8c40-f0a5d5bbfd9f.png) ![image](https://cloud.githubusercontent.com/assets/23368836/20506357/4a80fd1e-b008-11e6-96ae-d15a67d0f109.png) ![image](https://cloud.githubusercontent.com/assets/23368836/20506359/4cefc9c2-b008-11e6-81bc-097f75179cd3.png)

- [ ] Hyperlink each button to the following URLs respectively: 
     - [ ] https://www.facebook.com/SFWater
     - [ ] https://www.instagram.com/sfwater/     
     - [ ] https://twitter.com/SFWater]

**Comment by jszwedko** [comment]
@FrankieBurton @jeanwalshie I made the above changes and pushed to [staging](https://adoptadrainsf-staging.herokuapp.com/). Could you take a look and validate that they are what you expected (create a new user and then adopt a drain)?

**Comment by FrankieBurton** [comment]
Thanks @jszwedko! I am reviewing now.

**Comment by FrankieBurton** [comment]
@jszwedko How do I see these changes? The staging page only shows me the Adopt a Drain app. Where can I see the email content?

**Comment by jszwedko** [comment]
Hi @FrankieBurton, you'll need to register for a new account on the staging site and adopt a drain. It'll send you an e-mail afterwards.

**Comment by FrankieBurton** [comment]
Thanks for explaining @jszwedko! I'm in! 

Here are the missing edits:

1. Bold and hyperlink the text below to: http://www.sf311.org/index.aspx?page=127 (the link doesn't work).
"Report it to the City's Customer Service Center, 311 on the web (or dial 3-1-1)." 
2. Place at least one space between the three social media buttons.

**Comment by jszwedko** [comment]
@FrankieBurton cool, thank you for taking a look!

1. Can you forward the e-mail you got to [me](mailto:jesse.szwedko@gmail.com)? When I tried, I got an e-mail with the link as expected.
2. It looks like there is some space between the social media buttons already (see attached screenshot) -- do you see something different? Or do you want more space?

![2016-11-29-193308_1339x371_scrot](https://cloud.githubusercontent.com/assets/316880/20738816/d7e5c5f0-b66a-11e6-9d1b-087123b900fe.png)

**Comment by jszwedko** [comment]
Also, what e-mail client are you using? That might be affecting how it is rendering for you.

**Comment by FrankieBurton** [comment]
@jszwedko I emailed you.

**Comment by FrankieBurton** [comment]
@jszwedko I updated this issue to make the style consistent with what we requested for the website (see checklist at the top of the original issue). Please let me know if this cannot be done for some reason.

**Comment by jszwedko** [comment]
@FrankieBurton 👍 

A couple of points:

I took a look at Calbire and unfortunately it looks like it is a proprietary font so we would need to license it to use (https://www.fonts.com/font/microsoft-corporation/calibri). Is there another, free, sans-serif font that would be amenable?

"point" sizes for fonts are technically only valid for print media (rather than web), but the following looks like roughly equivalent `em` values:

* Title: 1.2em
* Heading: 1.05em
* Body: 1em

(em's are just ratios, 1.2em would be 120% of the "default" font-size which makes the experience better for users that use different default font sizes -- typically for accessibility)

**Comment by jszwedko** [comment]
Added inline styles for the header sizes but the page doesn't have a title per say.

**Comment by FrankieBurton** [comment]
@jszwedko Leave the font as is since we cannot use Calibri. Thanks!

**Comment by jeanwalshie** [comment]
hi all! i think this is pretty much good to go. i do (of course) have a couple teeny tiny suggested edits! :)
- remove the #stormprep hashtag, for reasons elaborated in another issue.
- remove the 1st instance of the word "periodic" from the "tools and training" paragraph. (it occurs twice)
- remove this sentence: "Want to encourage your coworkers, friends and neighbors to participate?" (don't think it's necessary.)

i think that's it, and we can make this live!

**Comment by jeanwalshie** [comment]
awesome, @jszwedko!

a couple more "nice to have" edits:
- stormwater is one word (1st paragraph, 3rd sentence). (i'm embarrassed submitting such a minor thing, but oh well.)
- i would like to remove the words "on the web" and shorten the hyperlinked text so it reads "Report it to the City's 311 Customer Service Center (hyperlinked) (or call 3-1-1). 

and that's it, we can close!

sorry and thank you!

**Comment by jszwedko** [comment]
No worries!

Made the edits in 249e451

Just let me know if there are any additional edits you need.

**Comment by jeanwalshie** [comment]
thank you, @jszwedko! I didn't test it, but I looked at the changes you made and they look perfect. closing this!
