### ISSUE TITLE
In database, have each drain represent a different row

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#20]
For clarity of data, each row should be its own drain, not as per status quo, which is each row represents a user, who can have multiple drains.

**Comment by afomi** [comment]
@hackajesse,

I believe this is the current state.

There is a `Thing`s table that holds things.. in this case, Drains.
There is also a `User`s table that holds images.

Each `Thing` has a `user_id` field that points to the `User` who has adopted the drain.
