### ISSUE TITLE
Replace text on the purple button.

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#204]
- [x] Replace text on the purple button with “What does it mean to adopt a drain? Click here to find out.”
- [ ] Change it to open a new tab when a user clicks on this button.

**Comment by jszwedko** [comment]
Similar to #209 I'll just keep the text in a modal for now, but when we design a new layout, we can move this to a separate page as well (if that's OK).

**Comment by FrankieBurton** [comment]
Sounds and looks great @jszwedko! :shipit:

**Comment by jeanwalshie** [comment]
we can close this, right?

**Comment by FrankieBurton** [comment]
Yeah I think so since this edit has been made and is live.
