### ISSUE TITLE
Replace text for “What does it mean to adopt a drain?” page.

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#206]
- [x] Replace text entirely with the text below.
- [ ] Change font on entire page to Calibri. 
- [x] Change the title to 14 point bold.
- [x] Change the heading to 13 point bold.
- [x] Change the body to 12 point normal.
- [x] Hyperlink Facebook button to: https://www.facebook.com/SFWater
- [x] Hyperlink Instagram button to: https://www.instagram.com/sfwater/
- [x] Hyperlink Twitter button to: https://twitter.com/SFWater

# What Does it Mean To Adopt a Drain?
Thank you for your interest in adopting one or more of San Francisco’s 25,000+ storm drains (also called catch basins). By pledging to keep your drain free of leaves and debris, you are joining your neighbors in helping to protect the environment, manage stormwater, and minimize flooding.

## How to Care For Your Adopted Drain 
•	If possible, clear the drain before it starts raining. 
•	Put leaves and other natural material in the green compost bin.  Put trash in the black garbage bin. 
•	Clear about 10 feet on both sides of the drain. 
•	Medical waste or needles? Construction debris? Toxic materials? **[Report it to the City’s Customer Service Center, 311 on the web](http://www.sf311.org/index.aspx?page=127) (or dial 3-1-1).**

## Drain Cleaning Safety Tips 
•	Never try to lift the drain grate. 
•	Clear from the sidewalk, not the street. 
•	Wear reflective clothing so vehicles can see you. 
•	Always wear gloves and be careful of sharp objects! 
•	Use a rake, broom, or shovel - not your hands. 

_Remember, the City and County of San Francisco won’t be held responsible for anything that happens to you or others in service of maintaining your drain. Please be careful!_

## Free Tools and Training 
We invite drain adopters to periodic events during the rainy season where they can receive drain cleaning trainings and free tools and supplies. Please keep an eye on your email for notification of these events. You will also receive periodic email reminders from the SFPUC to clear your drains when rain is expected.

## Spread the Word!
Excited about the Adopt a Drain program? Want to encourage your coworkers, friends and neighbors to participate? Utilize social media to spread the word. 

![image](https://cloud.githubusercontent.com/assets/23368836/21111453/762bc242-c056-11e6-9b88-d14e0c24b1c7.png) ![image](https://cloud.githubusercontent.com/assets/23368836/21111455/792be670-c056-11e6-861d-e61fe4defd8f.png) ![image](https://cloud.githubusercontent.com/assets/23368836/21111456/7b31f004-c056-11e6-8cf7-562688075d6e.png)
 	 	  
Remember to tag us [@SFWater](https://twitter.com/sfwater?lang=en) and to use the following hashtags: [#DrainHero](https://twitter.com/hashtag/drainhero), [#AdoptADrain](#AdoptADrain), [#StormPrep](https://twitter.com/hashtag/stormprep) and #[SFSewer](https://twitter.com/hashtag/sfsewer).

## Contact Us
Email questions and feedback to [info@sfwater.org](mailto:info@sfwater.org). We’d love to hear from you!

**Comment by jszwedko** [comment]
Updating the copy now, but same comment about the font family / sizes as over here: https://github.com/sfbrigade/adopt-a-drain/issues/199#issuecomment-267786909

**Comment by FrankieBurton** [comment]
@jszwedko here are my edits. 

- [ ] The text in the first paragraph should not be so big - it should match the other body text such as the text under "Free Tools and Training." 
- [ ] Bold section headers: How to Care For Your Adopted Drain, Drain Cleaning Safety Tips, Free Tools and Training, Spread the Word! and Contact Us.
- [ ] The 311 link loaded for a long time and never loaded. Please look into that.

**Comment by jeanwalshie** [comment]
hi all, this is looking great and i'd love to make it live! 

the 311 link worked for me just now, so who knows what the issue was.

two more teeny tiny things: 
1) there is an extra period after web in "on the web**.** (or dial 311).
2) let's remove the second instance of "periodic" as it occurs twice: "We invite drain adopters to periodic events during the rainy season where they can receive drain cleaning trainings and free tools and supplies. Please keep an eye on your email for notification of these events. You will also receive **periodic** email reminders..."

thanks!

**Comment by jszwedko** [comment]
:+1: made the above updates and pushed to the http://adoptadrainsf-staging.herokuapp.com/ as part of #201

**Comment by jszwedko** [comment]
No worries! Removed in bff46fe

**Comment by jeanwalshie** [comment]
this looks great! i'm closing the issue. thanks @jszwedko!!!
