### ISSUE TITLE
Replace text for the  “Adopt a Drain SF Background” page and rename button "Program Background"

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#207]
- [x] Replace text entirely with the text below.
- [ ] Change font on entre page to Calibri. 
- [x] Change the title to 14 point bold.
- [x] Change the heading to 13 point bold.
- [x] Change the body to 12 point normal.
- [x] Hyperlink circular GitHub button to https://github.com/sfbrigade/adopt-a-drain. 
- [x] Hyperlink GitHub watch button to watch the adopt a drain GitHub page. 
- [ ] If possible make headers collapsable and expandable.

# Adopt a Drain SF Background
## Adopt a Drain 
The Adopt a Drain program empowers San Franciscans to "adopt" one or more of the City's 25,000 storm drains (also called catch basins) and pledge to keep it free of leaves and debris. The program helps reduce localized flooding and fosters community engagement by empowering residents and business owners to show their love of the City by taking an active role in taking care of and improving the neighborhood where they live and work.

## Background
In late 2015, several San Francisco City agencies partnered with volunteers from [Code for San Francisco](http://codeforsanfrancisco.org/) to develop the Adopt a Drain SF web application.

The San Francisco Public Utilities Commission (SFPUC), the agency that manages the sewer system, including 25,000+ catch basins and storm drains, and San Francisco Public Works, the agency that maintains the database of sewer infrastructure assets, worked with the City's Open Data Program in the Mayor's Office to get the storm drain location data uploaded to the [City's Open Data Portal](https://data.sfgov.org/) (SF Open Data).

Code for San Francisco volunteers used a web-based platform called [GitHub](https://github.com/sfbrigade/adopt-a-drain) to develop the open source web application on [Ruby on Rails](http://rubyonrails.org/). GitHub enabled contributors to work on the project from anywhere in the world. They modeled Adopt a Drain San Francisco on Boston's [Adopt a Hydrant](http://www.adoptahydrant.org/), for which Code for America had provided initial support to develop in 2012. Approximately 25 people contributed to coding and developing the app.

## Volunteer Developer Opportunities 
Are you a programmer with Ruby on Rails experience who wants to help improve and maintain the Adopt a Drain application? Don’t be shy! We’re always **seeking assistance with the code**! Click on the buttons below to view and follow our GitHub page.  
![image](https://cloud.githubusercontent.com/assets/23368836/21112392/78589db6-c05a-11e6-942e-38e58d854206.png)  ![image](https://cloud.githubusercontent.com/assets/23368836/21112396/7bea89c6-c05a-11e6-86ca-de5ffeeb3ac1.png)

[Click here for more information about what it means to adopt a drain.](https://adoptadrain.sfwater.org/#background)

## Contact
Email questions and feedback to [info@sfwater.org](mailto:info@sfwater.org?subject=Adopt%20a%20Drain%20San%20Francisco). We’d love to hear from you!

**Comment by jszwedko** [comment]
👍  I like this copy

**Comment by jszwedko** [comment]
I unfortunately wasn't able to easily get the "Click here for more information about what it means to adopt a drain." link to function correctly in the modal (without breaking the scrolling) so I dropped it from the above copy. If is important though, I can spend some more time with it.

**Comment by FrankieBurton** [comment]
Let me ask @jeanwalshie about that @jszwedko. Add it to the nice to have list for now.

- [ ] Please bold the section headers: Adopt a Drain, Background, Volunteer Developer Opportunities and Contact. 
- [ ] Please remove the blue Github button since they both lead to the same page. Is it possible to open them in a new tab by default?

**Comment by jeanwalshie** [comment]
@FrankieBurton -- re item #3 above, we can make a new issue and tag it "nice to have". i'll do that now.

**Comment by jszwedko** [comment]
@FrankieBurton 

Apologies for the delay! The holidays have busy.

I removed the github icon, but the headers are already weighted (bold) did you want the weight to be heavier? See image for example of what it currently looks like (reminder that this is only on the staging server):

![screen shot 2016-12-26 at 12 37 29 pm](https://cloud.githubusercontent.com/assets/316880/21484895/2410137e-cb68-11e6-9595-07c43299e515.png)

Thank you!

**Comment by jeanwalshie** [comment]
hi @jszwedko, thanks for making these edits!

i would really like to make these content items live and worry about any formatting/font issues later if need be. what do you think?

**Comment by FrankieBurton** [comment]
@jszwedko That is not what it looks like for me, but I agree with @jeanwalshie. Let's make these edits live and then fix the headings. I'll take a look after it goes live and will let you know if there is an issue. Thanks!

**Comment by jszwedko** [comment]
Pushed another change up (to http://adoptadrainsf-staging.herokuapp.com/) that should hopefully fix the font-weighting issue across browsers. Let me know if it looks good to you @FrankieBurton !

**Comment by jeanwalshie** [comment]
@jszwedko this looks great, thank you! 

only one small thing: there is a duplicate paragraph. the first instance of "Code for San Francisco and other volunteers then used a web-based platform called Github to develop the open source web application on Ruby on Rails. Github enabled contributors to work on the project from anywhere in the world. They modeled Adopt a Drain SF on Boston's Adopt a Hydrant, for which Code for America had provided initial support to develop in 2012" should be removed. 

then i think we're good to go for this issue.

**Comment by jeanwalshie** [comment]
yay! closing this. THANK YOU.
