### ISSUE TITLE
Create blue button similar to purple button.

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#209]
- [x] Place the blue button below the Register/Sign in button and above the logos.
- [x] Include the following text on the blue button: “Learn more about the program.”
- [x] Hyperlink the blue button to open the “Adopt a Drain SF Background?” page in a new tab: https://adoptadrain.sfwater.org/#background

**Comment by jszwedko** [comment]
Hi @FrankieBurton, I think this is reasonable, however the app is currently a single page app so it would take a bit more work to design a new layout just for this page. What would you think of just making the placement and language updates for now, but keep the modal? And then, if we still want to have it appear on a separate page, we can tackle that in a second pass?

**Comment by FrankieBurton** [comment]
Hi @jszwedko! I think the issue here is the "learn  more" link is too small and is buried by the logos. We think the information on the Adopt a Drain SF Background page is important and want users to read it. The tiny learn more link is unlikely to be noticed. How do you suggest we address this issue? Do we have to create a new modal to add a button?

**Comment by jszwedko** [comment]
Ah! No, I agree with you that it isn't very prominent currently and agree with the changes to make it more so. I was mostly talking about whether, when clicked, it would open the modal (as it currently does) or if it would open a completely new page in a new browser tab (which would take a bit more work to design a layout for).

**Comment by FrankieBurton** [comment]
Oh! Thanks for explaining. I misunderstood your terminology. If it is going to take a lot more work to open it in a new tab then by all means keep it as is and table the new tab item for future versions. Do we have a thread going for "nice to haves"? If not can we start one? Or what is your preferred method for tracking those items?

**Comment by jszwedko** [comment]
👍  👍 

For the follow up, I think creating an issue for it is more than reasonable. I've created https://github.com/sfbrigade/adopt-a-drain/issues/211 and as well as a new `nice to have` label that we can use.

**Comment by jszwedko** [comment]
(I've also added you as a collaborator on the repo so that you can do things like label issues 😄 )

**Comment by FrankieBurton** [comment]
You read my mind!! I was about to ask about that since I cannot currently label issues. :D Thanks!

**Comment by FrankieBurton** [comment]
:shipit:

**Comment by FrankieBurton** [comment]
I reviewed and this looks great @jszwedko! :shipit:

**Comment by jeanwalshie** [comment]
hi guys,

this looks great, thank you! one SMALL suggestion: Can we call the button **Program Background**? it's a bit shorter and simpler, more accurately reflects the content, plus, i'm not a fan of the period at the end of the existing text as it's not consistent with other buttons.

**Comment by FrankieBurton** [comment]
I like that better!

**Comment by jszwedko** [comment]
:+1: Made the above update and pushed to http://adoptadrainsf-staging.herokuapp.com/ as part of #201

**Comment by jeanwalshie** [comment]
looks good @jszwedko i think we're ready to roll. can we close this one or should we wait til you make it officially live? i love closing issues! (it's really the only thing i'm good for around here... :)
