### ISSUE TITLE
Change "send feedback" mail to info@sfwater.org

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#21]

**Comment by jeanwalshie** [comment]
hi all, should feedback go to info@sfwater.org or code for sf?

**Comment by jszwedko** [comment]
I'm open to either as long as someone would follow up to any mail sent to `info@sfwater.org` and create issues here for technical questions / problems.

**Comment by jeanwalshie** [comment]
Thanks @jszwedko -- let's use info@sfwater.org. We have a team of folks responding to that email address and they will be sure to notify me, and I can pass along as appropriate.

**Comment by jszwedko** [comment]
:+1: thanks for the clarification!

**Comment by jeanwalshie** [comment]
i've sent a few test emails to the current address adoptadrain@codeforsanfrancisco.org and no one has replied :) . i think this is important so i added the mvp label.

**Comment by jszwedko** [comment]
:+1: agreed! I'm not sure who owns that e-mail.

**Comment by jeanwalshie** [comment]
thanks!!!
