### ISSUE TITLE
Remove the “send feedback” link and “Learn More” link. 

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#210]
Once Issues #203, #204, #206, #207, #208 and #209 are complete remove the “send feedback” link and “Learn More” link from the bottom of the page.

**Comment by FrankieBurton** [comment]
Reviewed and this looks good! :shipit:

**Comment by jszwedko** [comment]
Awesome, thank you. I haven't circled back to the logos yet, but will do so (I'd like to get #201 out first just to close out most of the issues since this once might end up being a bigger change).

**Comment by jeanwalshie** [comment]
i'm gonna close this because i see the links have been removed.
