### ISSUE TITLE
Have links open in a new window

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#212]
ie, in Program Background modal, have links to Github, Code for San Francisco, Open Data Portal, Ruby on Rails, etc. open in a new window.

**Comment by jeanwalshie** [comment]
hey @jafowler49 what's the next step on this? i guess i'm unclear on who's supposed to review before it goes live.

**Comment by jafowler49** [comment]
Hey Jean,

I think Jesse was the final reviewer, the one who merges branches. But maybe I'm wrong...

@jszwedko for all Pull Requests, should I merge them into production myself, or do you do that? 

Also, the second pull request that I opened has a minor error - I didn't create the branch off the production branch so the two pull requests share the same commits. I can fix this if necessary

Thanks!

**Comment by jszwedko** [comment]
Historically, I have reviewed incoming code as well as merged my own in, but now that we have multiple maintainers, I would definitely appreciate review of my PRs (if that is cool with you @jafowler49) and I'm happy to review incoming.

**Comment by jszwedko** [comment]
@jeanwalshie double checked this on staging and promoted to production if you want to take a look.

**Comment by jeanwalshie** [comment]
this is solid! much better. 
ready to close this issue, but i see there's an outstanding question about review for @jafowler49. i'll keep it open for now. thanks, guys!

**Comment by jafowler49** [comment]
Hi @jeanwalshie, Jesse answered my question so you are free to close this
