### ISSUE TITLE
change the email sender from "info" to "Adopt a Drain SF"

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#214]
the reply to address should remain info@sfwater.org but i'm hoping we can change the sender to something more descriptive than "info".

gracias!

**Comment by jszwedko** [comment]
Good idea! Addressed in https://github.com/sfbrigade/adopt-a-drain/commit/fd816b0494a9430046b768d1c3eb10c212c81e29
