### ISSUE TITLE
Name not showing up after adoption/orange icon not appearing for adopted drain

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#215]
hmmm, i adopted a drain and named it, but the name is only showing up in the sidebar of my drains, not on the actual drain i adopted. there it just says "catch basin drain has been adopted..."

i wonder if this happened because we imported a new batch of drain data? @jasonlally

**Comment by jszwedko** [comment]
@jeanwalshie I don't think we've run an import for quite a while (looks like 2016-01-13), but you are right that there exists a bug whereby it would overwrite the name the user gave the drain. We should aim to fix that before running any more imports. When did you adopt the drain in question? For reference, my adopted drains still have the names I gave them.

This also affects #198.

**Comment by jeanwalshie** [comment]
I recently (can't remember the date - past few weeks) un-adopted my drain and re-adopted it, giving it a name. the name shows up in the sidebar but not on the actual drain icon. also, my adopted drain is not showing up as orange... hmmm.

**Comment by jszwedko** [comment]
@jeanwalshie I'm still not sure I completely understand. I was able to un-adopt and re-adopt a drain, giving it a new name, and it seemed to work OK. Note that the sidebar does not dynamically update, but will upon page refresh.

**Comment by jeanwalshie** [comment]
I'm sorry, @jszwedko. I think I figured it out. When a user is logged in his/her drain name will not show up on the actual drain. There it will just say "Thank you for adopting this drain." So that's fine. (When I log out and view the drain, the drain name does show on the map.)

BUT -- there is still the issue of my adopted drain's icon not being orange, but showing up as gray. 

I can make a new issue or change the name of this one if needed...

**Comment by jszwedko** [comment]
Aah, hmm, was it gray when you were logged in? When you are not logged in that it will show it as gray since it doesn't know it is your drain.

**Comment by jszwedko** [comment]
@jeanwalshie just checking in to see if you are still seeing an issue.

**Comment by jeanwalshie** [comment]
yes, sorry @jszwedko! i was out of town on a 10-day silent meditation retreat -- just coming up for air. 

and yes, the icon for my adopted drain is showing up as gray (vs. orange) when i'm logged in. my drain is the one at 20th and S. Van Ness in the image below. 

it's a small thing, but still a bug. thanks so much for following up!

![image](https://cloud.githubusercontent.com/assets/15933453/22477598/92a50c8c-e79b-11e6-9232-1aa646ed6994.png)

**Comment by jszwedko** [comment]
@jeanwalshie no worries! That sounds amazing.

Thanks for the screenshot, that helped me figure out that I had inadvertently broke the highlighting of adopted drains during #196. I re-added the missing field and added a test to make sure it isn't accidentally removed in the future in f3fc31a.

**Comment by jeanwalshie** [comment]
perfect! I think this is done!
