### ISSUE TITLE
make last name a requirement for new sign-ups

### ISSUE THREAD

**Issue by idilbereket** [sfbrigade/adopt-a-drain#221]
I'm posting on behalf of the SFPUC: As we import this new data to our contact database, not having a last name is a problem.

**Comment by jeanwalshie** [comment]
yes, i agree and would like to try this.

**Comment by jszwedko** [comment]
:+1: it'd be nice to have some metrics to see if there is any drop-off when that requirement is added, but hopefully most people don't find it too invasive.

**Comment by idilbereket** [comment]
yes agreed, thanks for replying quickly @jszwedko .

**Comment by idilbereket** [comment]
Exciting to see 1345 drains adopted by 842 people! With that, wanted to check on "making the last name as a requirement for the new sign-ups". Thanks much!

**Comment by jszwedko** [comment]
@idilbereket I've implemented this (but have not released yet) in #223. I ended up implementing it to only require the last name field for new users to avoid existing users getting, what I would imagine would be, confusing errors when updating their profile.

Let me know what you think and I'll release it.

**Comment by idilbereket** [comment]
@jszwedko that sounds good - you're right, best if it's a requirement for newcomers only, and we can keep as is for the existing users. Also, will you be removing the word "optional" for last name? Thanks much!

**Comment by jszwedko** [comment]
@idilbereket awesome, I'll release it now. And yep, I removed the `Optional` label from that field.

**Comment by idilbereket** [comment]
Awesome @jszwedko ! I also saw the tracker (for the number of drains adopters) is now on - yay! Thanks for all your help!!!

**Comment by jszwedko** [comment]
Of course!
