### ISSUE TITLE
Rename columns in Admin area

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#224]
In the "List of Drains" section of the Admin area there are several columns we would like to rename to make them more clear:

1) "Created at:" If this represents the date the drain was imported into the system, can we call it "Drain Import Date"? They all say 12/8/2015 so i assume that's what this means. If not, please clarify. 
2) "Updated at:" Does this represent the date the drain was adopted? or renamed? ore either one? the dates range from 1/13/16 to the present. Maybe we can name this something more clear if at all possible. (on a side note, what date will be shown if the date is not adopted? Maybe that can say N/A)

In the "Users" section:
1) "Created at": does this mean the date the user account was created? If so, let's rename "Account Creation Date" or "User Account Created" or something. 
2) "Updated at" seems to mean last user log in date. If so, let's rename "Last Log In".

**Comment by jeanwalshie** [comment]
PS, tagging this UX because Admins are users too! :)

**Comment by jszwedko** [comment]
:+1: admins are definitely also users :)

Unfortunately the admin side is using a generic Rails admin plugin so created_at/updated_at fields map directly to "record" terminology, but I think we should be able to make some labeling adjustments.

To answer your questions:

> "Created at:" If this represents the date the drain was imported into the system, can we call it "Drain Import Date"? They all say 12/8/2015 so i assume that's what this means. If not, please clarify.

Correct, this is when the record was created in the database (which is generally only during the import).

> "Updated at:" Does this represent the date the drain was adopted? or renamed? ore either one? the dates range from 1/13/16 to the present. Maybe we can name this something more clear if at all possible. (on a side note, what date will be shown if the date is not adopted? Maybe that can say N/A)
In the "Users" section:

This is the last time any field on the record was modified. Typically this happens during adoption, when the `user_id` field is populated, but would also likely happen during any future imports.

> "Created at": does this mean the date the user account was created? If so, let's rename "Account Creation Date" or "User Account Created" or something.

Indeed, this is when the user record was created (which generally only happens during registration, but you can also add users manually in the admin area).

> "Updated at" seems to mean last user log in date. If so, let's rename "Last Log In".

Similar to above, this is when any field on the user is modified (this does happen during login, where the `current_sign_in_at` field is updated), but can also happen if the user modifies their name or other elements of their profile. However, to determine their last login, you can use `current_sign_in_at` field (which you can see if you click to view the details of a given user).

Outside of these fields, if there is anything in particular you'd like to capture about users and drains that is currently being captured, we can certainly add fields to hold that information, but does the above information change how you might like to see these fields labeled?

**Comment by jeanwalshie** [comment]
Thanks, @jszwedko! 

i think we should relabel if possible.
1) in the Drains section RENAME "Created at:" to "Drain Import Date"
2) in the Drains section LEAVE AS IS "Updated at"
3) In the Users section RENAME "Created at" to "Account Creation Date"
4) in the Users section RENAME "Updated at" to "Last Log In". (Since any change made by the user would require the user to log in, that's in fact what this column means)

otherwise it's not at all intuitive what "created at" and "updated at" mean, and it's different depending on whether you're in the Drains or Users section. This will make it much more clear to an admin what they are looking at. 

however, is it even possible to relabel these things in Ruby?

thanks again!

**Comment by jeanwalshie** [comment]
this is awesome! so much easier on the admin end. i think we can close this. thanks @jafowler49 and @jszwedko!
