### ISSUE TITLE
Remove time stamp from # of drains adopted ticker

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#226]
small thing, but the time stamp seems to be Eastern Standard and military time, and i think it's unnecessary. i'd like to remove it but keep the full date. ie, Last updated February 7th, 2017 (REMOVE 22:30)

**Comment by jszwedko** [comment]
Aha, yes, of course, I neglected that it would use the server timezone. I'll remove the time.

**Comment by jszwedko** [comment]
Just committed this directly since it was a small change -- it's been merged and released.
