### ISSUE TITLE
Change name of "City" column in Admin area

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#231]
For some reason the "City" column in the Admin area lists a five digit number that corresponds to the drain number in our Maximo asset management system. I would like to rename that column Maximo ID. @jafowler49 is that something you can help with?

**Comment by jafowler49** [comment]
cool, yea I'll add a column alias as I did with the updated_at column

**Comment by jafowler49** [comment]
Completed @ https://github.com/sfbrigade/adopt-a-drain/pull/233

This can be closed

**Comment by jeanwalshie** [comment]
awesome, thanks!!!
