### ISSUE TITLE
Add DT logo to UI

### ISSUE THREAD

**Issue by jafowler49** [sfbrigade/adopt-a-drain#234]
With @jeanwalshie approval, per our conversation a while ago, add a Department of Techonology logo somewhere on the UI. I'm thinking next to "Code for America" logo, which would move that the right and have DT logo on the left. Gonna upload a comp so we can see it.

**Comment by jeanwalshie** [comment]
hi @jafowler49 -- yes, absolutely! we were discussing this here #208. I would still like to fix scaling issue with the SFPUC and Public Works logos. Maybe you can tackle while you're adding the DT one? I emailed vector logos to @jszwedko and can send them again if you need them.

**Comment by jafowler49** [comment]
sure can you email me the logos that you emailed to Jesse? my email is james.fowler@sfgov.org . thanks!

**Comment by jafowler49** [comment]
Added to pull request https://github.com/sfbrigade/adopt-a-drain/pull/237

**Comment by jszwedko** [comment]
@jafowler49 apologies, just circling back to this now, but I've added you as an admin in adopt-a-drain and as a collaborator on the Heroku projects.

**Comment by jeanwalshie** [comment]
hey, the logos look great! but now the video isn't showing up for me... i'll open another issue for this. i think this one can be closed! thanks @jafowler49 !

**Comment by jszwedko** [comment]
@jeanwalshie note that the video only shows up when you are not signed in (I was able to see it when logged out).

**Comment by jeanwalshie** [comment]
@jszwedko thanks -- but there's a white space where the video normally is. i don't remember that space being there... did something change?

**Comment by jszwedko** [comment]
Hmm, when you are signed in? Or not signed in?

This is what I see when not signed in:

![2017-04-25-152507_464x666_scrot](https://cloud.githubusercontent.com/assets/316880/25410400/6c4e4c98-29cb-11e7-8371-22c55f54fd72.png)

**Comment by jeanwalshie** [comment]
sorry! in chrome, when signed in, here's what i see: 
![image](https://cloud.githubusercontent.com/assets/15933453/25410431/9c16f178-29cb-11e7-9156-6b930f70bdc9.png)

**Comment by jszwedko** [comment]
Aaah, yes, I see, that is a result of these changes; I neglected to test with a smaller number of drains. I'll adjust that now.

**Comment by jszwedko** [comment]
@jeanwalshie made the changes in #239 and pushed to staging (http://adoptadrainsf-staging.herokuapp.com/) if you have a chance to take a look.

**Comment by jeanwalshie** [comment]
awesome, thanks! i forgot the password for the staging site -- sorry! (mine doesn't work.)

**Comment by jszwedko** [comment]
@jeanwalshie :+1: you can feel free to create additional accounts there (or reset your password).

**Comment by jeanwalshie** [comment]
oh! so sorry -- i thought there was a separate staging password. i'm clearly doing too many things at once. you are a patient man. 

looks great! :)

**Comment by jszwedko** [comment]
No worries! Thanks for checking it out. I'll promote it.

**Comment by jszwedko** [comment]
Apologies, I keep forgetting Github will autoclose issues from PRs. I'll stop using the keywords it looks for to do that.
