### ISSUE TITLE
Enforce "Stay Signed In" choice

### ISSUE THREAD

**Issue by jafowler49** [sfbrigade/adopt-a-drain#235]
Whether or not the user chooses "Stay Signed In" when they sign on, the user stays authenticated 

To Replicate: 
1) At sign in screen, uncheck "Stay Signed In"
2) Sign in
3) Quit browser
4) Open browser and go back to Adopt a Drain
5) Notice user still signed in

Desired Behavior is that on browser close, users stay authenticated only when they chose "Stay Signed on"

If this is in fact an issue, I can fix it. But maybe it's not and I'm missing something! Thanks

**Comment by jeanwalshie** [comment]
good catch! I think if we are giving the option we should follow through on whatever they select.

**Comment by jszwedko** [comment]
@jafowler49 good catch, it does appear to be setting the cookie either way.
