### ISSUE TITLE
problem logging in the back-end

### ISSUE THREAD

**Issue by idilbereket** [sfbrigade/adopt-a-drain#238]
Hello, I am from the SFPUC and have been one of the administrators and logging in on the back-end. Today, it's no longer allowing me to access the admin site. Can you help? I have not changed my username and password. Here is a screenshot. Thank you!
![aad - unable to login on admin site](https://cloud.githubusercontent.com/assets/23368936/25350234/521411ca-28d9-11e7-992c-d90cfde40e2b.JPG)

**Comment by jszwedko** [comment]
Apologies @idilbereket, we were doing some clean up and must have inadvertently removed your access. This should be fixed now, let me know if it still doesn't work!

**Comment by idilbereket** [comment]
Thanks much for fixing it super quickly! It's working now.

**Comment by jszwedko** [comment]
No problem! Closing this out, but let me know if you have any other issues.
