### ISSUE TITLE
How to see who the Admins are? (and make a change)

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#242]
hello team - 

1) i'm wondering if there is a way to see who the admins are on the back end
2) i would also like to change my admin email from gmail to my city email

thank you in advance @jszwedko @jafowler49 !

**Comment by jszwedko** [comment]
Hi @jeanwalshie 

You can see the current admins here: https://adoptadrain.sfwater.org/admin/user?model_name=user&utf8=%E2%9C%93&f%5Badmin%5D%5B41771%5D%5Bv%5D=true&query=

If you navigate to a user, you can check the "Admin" box for that user:

![2017-05-30-121042_207x63_scrot](https://cloud.githubusercontent.com/assets/316880/26595465/199bc85a-4531-11e7-9f89-656520ebca41.png)

Hope this helps!

**Comment by jszwedko** [comment]
(I also updated your user's email to the @sfwater.org address -- you'll need to use this one when logging in now)

**Comment by jszwedko** [comment]
Scratch that, I see there is already a user with that address. Instead, made the other user an admin.

**Comment by jeanwalshie** [comment]
got it, so do a filter for admin = true. 

great, i'll close this. thanks @jszwedko!
