### ISSUE TITLE
"Reminders" section on admin site

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#243]
Under Navigation there are three things: Drains, Reminders and Users. 

What is "Reminders" for? 

If this feature isn't being used and we don't see a use for it, do have the option of removing it?

**Comment by jszwedko** [comment]
The "Reminders" feature did originally permit admins to send messages to the user that adopted a given drain via a button in the popup that appears when clicking on an adopted drain, but it was removed from in #105 

If we don't see any use for it, I'd be OK with dropping it completely.

**Comment by jeanwalshie** [comment]
hmmm, ok, let's keep it for now. who knows, we may want to bring it back to life at some point. thanks @jszwedko!
