### ISSUE TITLE
Add Branding to App Generated Emails?

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#244]
Hi there, 

Is it possible to add branding to the emails an adopter receives when they adopt one or more drains? For example we'd like to include the logo so it better matches the Salesforce generated emails. 

Thanks!

**Comment by jszwedko** [comment]
For sure, can you describe what you would like to see in them?

**Comment by jeanwalshie** [comment]
hi @jszwedko and welcome back from your travels!
i think @FrankieBurton was wanting to add the SFPUC/Adopt a Drain logo to the outbound emails. we are also looking at refreshing those emails, so we can hold off on this for now.

**Comment by jeanwalshie** [comment]
@frankieburton do you want to close this issue since you created two new issues? thanks.
