### ISSUE TITLE
Revisions to the Email Received After Adopting One Drain

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#245]
- [ ] Change the first email subject to: Thanks for adopting a drain, [Name]! 

- [ ] Include the image below as the header of the email and center it. 
![image](https://user-images.githubusercontent.com/23368836/27504937-09a5176e-5849-11e7-8368-cc330c30f24d.png)

- [ ] Replace the existing text with the text and images below using Arial 12 pt font. 

Dear (NAME),

Thank you for adopting one of San Francisco's 25,000 catch basins/storm drains and keeping it free of leaves and debris. You are joining your neighbors in helping to protect the environment, manage stormwater, and minimize flooding. 

**How to Care For Your Adopted Drain**
•	If possible, clear the drain before and after it rains. 
•	Put leaves and other natural material in the green compost bin. 
•	Put trash in the black garbage bin. 
•	Clear about 10 feet on both sides of the drain. 
•	Medical waste or needles? Construction debris? Drain clogged underneath the grate? [Report to 311](http://www.sf311.org/index.aspx?page=127) to have it handled by the City.

**Drain Cleaning Safety Tips**
•	Never try to lift the drain grate. 
•	Clear from the sidewalk, not the street. 
•	Wear reflective clothing so vehicles can see you. 
•	Always wear gloves and be very careful of sharp objects. 
•	Use a rake, broom, or shovel - not your hands. 

![image](https://user-images.githubusercontent.com/23368836/27504961-68fab016-5849-11e7-8a77-b7202449aa28.png)
_Adopt a Drain VIP event_ [**GitHub note: --> use Arial 10 pt font**]

Keep an eye out for an email invitation to attend one of our VIP Volunteer events, where you will be able to receive drain cleaning tools and training. We also send periodic email reminders to clear your drains. 

Thanks again, [Name], for adopting a drain in San Francisco. When each of us helps out a little, it makes a big difference! 
Sincerely, 
SFPUC [Adopt a Drain](https://adoptadrain.sfwater.org/) Team
[415-554-3289](tel:415-554-3289) 
[info@sfwater.org ](mailto:info@sfwater.org)

_Remember, the City and County of San Francisco won't be held responsible for anything that happens to you or others in service of maintaining your drain. Please be careful._

_If you move or are no longer able to tend to your drain, please abandon it on [adoptadrain.sfwater.org](www.adoptadrain.sfwater.org). Thank you._ [**GitHub note: --> use Arial 11 pt font**]

- [ ] Insert and hyperlink the buttons as shown below.
![image](https://user-images.githubusercontent.com/23368836/27505059-3e2ce118-584b-11e7-8e19-6ba63253b3cd.png)

- [ ] Insert the button below ![image](https://user-images.githubusercontent.com/23368836/27505009-287ecde6-584a-11e7-8791-59c0c606853e.png) and hyperlink it to https://facebook.com/sfwater.

- [ ] Insert the button below ![image](https://user-images.githubusercontent.com/23368836/27505023-6639aa48-584a-11e7-9404-e1af83159468.png) and hyperlink it to https://twitter.com/sfwater.

- [ ] Insert the button below 
![image](https://user-images.githubusercontent.com/23368836/27505030-7b494790-584a-11e7-9cf0-a3c090d38414.png) and hyperlink it to https://instagram.com/sfwater.

- [ ] Insert the button below 
![image](https://user-images.githubusercontent.com/23368836/27505035-8bc7d96a-584a-11e7-8543-c1bcd069d31b.png) and hyperlink it to https://www.youtube.com/user/SFPUCcommunications.

- [ ] Insert the button below 
![image](https://user-images.githubusercontent.com/23368836/27505038-9e06e92c-584a-11e7-9688-93f0fae67284.png) and hyperlink it to https://www.linkedin.com/company/sfpuc.

**Comment by FrankieBurton** [comment]
@jasonlally What is the status of this request?

**Comment by FrankieBurton** [comment]
@jszwedko It does not appear this email has been updated. We checked the staging site and the live site. I'll send you an email.

**Comment by FrankieBurton** [comment]
@jszwedko It does not appear this email has been updated. We checked the staging site and the live site. I'll send you an email. @jasonlally can you help with this request?

**Comment by jszwedko** [comment]
Closing this since #250 was released
