### ISSUE TITLE
Coordinate domain purchasing/subdomains

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#25]
@jasonlally please coordinate with Jean and update this issue w/status

**Comment by jasonlally** [comment]
Still waiting on this.

**Comment by jasonlally** [comment]
Subdomain exists and is pointing to the server, heroku needs to be configured.

@hackajesse should we do this now, or wait until launch?

**Comment by hackajesse** [comment]
@jasonlally was there a determined launch date?





On Mon, Dec 7, 2015 at 9:10 AM -0800, "Jason Lally" <notifications@github.com> wrote:












Subdomain exists and is pointing to the server, heroku needs to be configured.



@hackajesse should we do this now, or wait until launch?

**Comment by afomi** [comment]
what is the domain?

**Comment by jasonlally** [comment]
adoptadrain.sfwater.org

@hackajesse in terms of dates, we're aiming to wrap things before 12/14 for a presentation. Soft launch for subset of City users will be through December after or just before 12/14. For all purposes we should consider that the MVP and then fine-tuning, small adjustments through January.

**Comment by afomi** [comment]
adoptadrainsf.herokuapp.com can now be `CNAME`d from adoptadrain.sfwater.org

**Comment by jszwedko** [comment]
Closing this now that we have the subdomain pointing to the app, thanks @afomi !
