### ISSUE TITLE
Design changes to "What Does It Mean to Adopt a Drain?" button

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#252]
I would like to do two things to this button:
1) remove the text that says "Click here..." 
2) round the corners so it matches the other buttons on the page. 

thank you!

**Comment by jszwedko** [comment]
Changes visible here: https://adoptadrainsf-staging-pr-256.herokuapp.com/

Note that this does not include the changes from #247 #248 since they still need to be merged.

Let me know what you think @jeanwalshie !

**Comment by jeanwalshie** [comment]
looks good to me! thanks @jszwedko !

**Comment by jszwedko** [comment]
Released!
