### ISSUE TITLE
Revisions to the Email Received After Adopting One Drain

### ISSUE THREAD

**Issue by krwebb** [sfbrigade/adopt-a-drain#254]
#245 

- [ ] Change overall font to 12 pt, Arial. 

- [ ] Move the header image below to the left. Absolute position 1.5" to the right of Column.
![image](https://user-images.githubusercontent.com/23368836/27504937-09a5176e-5849-11e7-8368-cc330c30f24d.png)

- [ ] Add line space after > Dear Name, 

- [ ] Move the image below to the left. Absolute position 1.5" to the right of Column.
![image](https://user-images.githubusercontent.com/23368836/27504961-68fab016-5849-11e7-8a77-b7202449aa28.png)

- [ ] Add line space after > Keep an eye out for an email invitation to attend one of our VIP Volunteer events, where you will be able to receive drain cleaning tools and training. We also send periodic email reminders to clear your drains. 

- [ ] Add line space after > Thanks again, Kristen, for adopting a drain in San Francisco. When each of us helps out a little, it makes a big difference! 

- [ ] Add line space after > Sincerely,

- [ ] Add line space after > SFPUC Adopt a Drain Team 
415-554-3289 
info@sfwater.org 

- [ ] Add line space after > Remember, the City and County of San Francisco won't be held responsible for anything that happens to you or others in service of maintaining your drain. Please be careful. 

- [ ] Add line space after > If you move or are no longer able to tend to your drain, please abandon it on https://adoptadrain.sfwater.org. Thank you.

**Comment by jszwedko** [comment]
Hi @krwebb,

I think the e-mail currently reflects all of these (aside from the relative positioning of the images which are currently centered).

Here is an image of the top half of the e-mail which I just tested (ignore the black square; that was added by the screenshot tool):

![2017-08-09-142352_946x438_scrot](https://user-images.githubusercontent.com/316880/29144702-b9718db4-7d0e-11e7-9090-07e8b7fd7943.png)

Does it look different to you? If so, can you provide as many details as possible about the e-mail client you are using?

Thanks!

**Comment by krwebb** [comment]
Hi @jszwedko thank you for your help with the revisions. Can you please post the link of the test site again so I can review it one more time? The last I tested it on 8/03/17 and there were still some spacing issues. The middle has spaces but the top an bottom needed line spacing, see below. I will test it again once you post the link, perhaps you made edits after I tested it. Thank you!
  
![test email-one drain adopted_08_03_17](https://user-images.githubusercontent.com/30874055/29325313-062ee732-819c-11e7-8a0c-fb9a8d097495.jpg)

**Comment by jszwedko** [comment]
Hi @krwebb,

Both production and the staging site are up-to-date with the changes if you want to try one of those again.

Here is what the bottom looks like to me:

![2017-08-15-094257_852x313_scrot](https://user-images.githubusercontent.com/316880/29325885-3a51755a-819e-11e7-8251-49cf6120c75f.png)

**Comment by jszwedko** [comment]
Hi @krwebb,

Just checking in on this to see if you had a chance to reverify.

Thanks!

**Comment by krwebb** [comment]
Hi @jszwedko ,

Thank you for following up. I am just getting to checking this however when I tried to access the temporary application, the link is dead. Can you re-post or should I test it from the actual app? 

Thank you,

Kristen

**Comment by jeanwalshie** [comment]
hi @krwebb see if this works. I grabbed it from a closed issue - you can do the same if need be next time: http://adoptadrainsf-staging.herokuapp.com/

**Comment by krwebb** [comment]
Hi,

Thanks @jeanwalshie that link worked to test the auto emails. Thank you again @jszwedko for all of your work on this. The line spacing looks good for the most part. Both emails need a line space after the closing line, "Sincerely", before "SFPUC Adopt a Drain Team".  In the email after adopting two drains, please add a line space after the first line, "Wow! Thank you for adopting another drain", before "Use social media to spread the word!"

Thank you!

Kristen

**Comment by jszwedko** [comment]
Hi @krwebb,

I've made these adjustments and deployed to a temporary app here: https://adoptadrainsf-staging-pr-264.herokuapp.com/

They were pretty small changes, but can you double check them? (Note: you'll need to register a new account since the application is temporary).

**Comment by krwebb** [comment]
Hi Jesse,

I tested and reviewed the revisions on the temporary application and all have been made. Thank you for your time, we really appreciate it.

Thanks again!

Kristen

**Comment by jszwedko** [comment]
Awesome! Merging in now.
