### ISSUE TITLE
Revisions to the Email Received After Adopting Two Drains

### ISSUE THREAD

**Issue by krwebb** [sfbrigade/adopt-a-drain#255]
#246 

- [ ] Change overall font to 12 pt, Arial. 

- [ ] Move the header image below to the left. Absolute position 1.5" to the right of Column.
![image](https://user-images.githubusercontent.com/23368836/27504937-09a5176e-5849-11e7-8368-cc330c30f24d.png)

- [ ] Add line space after > Dear Name, 

- [ ] Add line space after > Wow! Thank you for adopting another drain. 

- [ ] Add line space after > Use social media to spread the word! Be sure to tag us @sfwater and use the hashtags #DrainHero, #AdoptADrain and #SFSewer in your posts. 

- [ ] Add line space after > If you encounter medical waste, construction debris, or if the drain is clogged beneath the grate, report to 311 to have it cleared by the City. 

- [ ] Add line space after > As always, please let us know if you have any feedback or questions about this program. We love to hear from you. 

- [ ] Add line space after > Sincerely,

- [ ] Add line space after > SFPUC Adopt a Drain Team 
415-554-3289 
info@sfwater.org 

- [ ] Add line space after > Remember, the City and County of San Francisco won't be held responsible for anything that happens to you or others in service of maintaining your drain. Please be careful. 

- [ ] Add line space after > If you move or are no longer able to tend to your drain, please abandon it on https://adoptadrain.sfwater.org. Thank you.

**Comment by jeanwalshie** [comment]
@krwebb is this done? if so can we please close this issue?
