### ISSUE TITLE
Link SFPUC logo to the SFPUC Adopt a Drain webpage 

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#257]
We'd like the SFPUC logo (bottom left) to drive people to the Adopt a Drain page vs. the SFPUC home page.

This is the link: https://sfwater.org/index.aspx?page=1184

Thank you!
Jean

**Comment by jszwedko** [comment]
Deployed this change here: http://adoptadrainsf-staging-pr-258.herokuapp.com/

It is a pretty trivial change, but let me know what you think @jeanwalshie !

**Comment by jeanwalshie** [comment]
looks great! thanks!

**Comment by jszwedko** [comment]
Released!
