### ISSUE TITLE
Research and send legal liability stuff to Jean

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#26]
[] Copy legal from Oakland 
[] Copy any legal I can find from SF programs
[] Send to Jean

**Comment by jszwedko** [comment]
@hackajesse any update on this? (Just trying to wrap all of the MVP issues before the soft launch -- feel free to remove it from the milestone if it isn't required for the MVP).

**Comment by jszwedko** [comment]
cc/ @jasonlally

**Comment by jasonlally** [comment]
Everything is to Jean, I think we're still waiting on review of the language.

**Comment by hackajesse** [comment]
Same last I heard, too.





On Sat, Dec 19, 2015 at 10:10 AM -0800, "Jason Lally" <notifications@github.com> wrote:












Everything is to Jean, I think we're still waiting on review of the language.

**Comment by jszwedko** [comment]
:+1: thanks for the update!

**Comment by jasonlally** [comment]
This is done
