### ISSUE TITLE
Make Last Name Private on App Map

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#308]
Hi all,

An adopter pointed out that there is an inconsistency between the online registration form and the app. In the form we state that only the adopters first name will be visible to others and their last name will be private. On the final map, both the first and last names appear on the adopted drain.

Our preference is to remove the last name from appearing public on the the app map. Is that possible? If not, then please change the "Register/Sign in" form's Last Name field from "Last name (private)" to "Last name (visible to others)". 

Please let me know if you have any questions.

Thanks,
Frankie

**Comment by jszwedko** [comment]
Hi @FrankieBurton,

Thanks for pointing this out! I pushed an update that hides the name on the map to match the labeling. Feel free to close this out if it looks good to you!

**Comment by FrankieBurton** [comment]
Hi Jesse,

Yes, this looks great! Thanks!

[cid:image001.png@01D3CC04.41214030]

Frankie Burton
Account Supervisor
Katz & Associates<http://www.katzandassociates.com/>
310-347-8368 (c) | 628-220-2579 (d)
San Francisco <http://www.katzandassociates.com/contact/>  | Los Angeles <http://www.katzandassociates.com/contact/>  | San Diego<http://www.katzandassociates.com/contact/>

SPRING HAS SPRUNG (so has our latest newsletter!)
It’s a quick read this way<http://bit.ly/2G0mj2w>.

**Comment by jszwedko** [comment]
Great, thanks!
