### ISSUE TITLE
Support small screens

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#31]
Need: on mobile, the sidebar is difficult to use. Can we redesign to make it easier on mobile?

**Comment by hackajesse** [comment]
#53

**Comment by jszwedko** [comment]
@hackajesse did you mean to reopen this?

**Comment by hackajesse** [comment]
@jszwedko - I did - the issue didn't seem fully addressed. Might be good to create a more specific one at this point to clarify the need, etc.



– 
Jesse Biroscak

jesse.biroscak@gmail.com

c. 415.439.3164


[Li] [Tw]

**Comment by jszwedko** [comment]
@hackajesse Gotcha, yeah it would be nice to have more specifics for other enhancements. This issue mentions the sidebar which I think is in good shape now.

Do you mind if I close this one and we can open issues for additional specific mobile enhancements?

**Comment by jasonlally** [comment]
Let's go ahead and close this now as we support small screens now. There will likely be some additional issues related to firming up that support, but those belong in their own set of issues.
