### ISSUE TITLE
Clearly convey who users should contact if they can't clear their drain on the homepage

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#32]
311 app. 
Where to put this in the app?
 - confirmation email
 - expectations on homepage

**Comment by jszwedko** [comment]
I think this is covered by #70 -- is there anywhere else this information should appear @hackajesse ?

**Comment by jszwedko** [comment]
Also cc/ @jasonlally

**Comment by jasonlally** [comment]
This is covered by the email, but will also need to be incorporated into the UI as part of #65

**Comment by jasonlally** [comment]
I updated the title of this one to make it more specific

**Comment by jszwedko** [comment]
:+1: makes sense

**Comment by jszwedko** [comment]
Rolling this into #65
