### ISSUE TITLE
Convey the City is not responsible (legally)

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#33]
Likely in a modal w/the Ts & Cs.

**Comment by jszwedko** [comment]
@hackajesse any update on this? Is it still required for the MVP?

**Comment by jszwedko** [comment]
Just noticed we already have terms of service linked on the site courtesy of @jasonlally -- does that address this issue?

**Comment by jszwedko** [comment]
Closing since we have terms and conditions, but let me know if you meant something else @hackajesse
