### ISSUE TITLE
Make it clear people know what they're committing to when adopting

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#34]
Could be as simple as editing the modal or as complex as a landing page. Will definitely require multiple versions.

**Comment by jszwedko** [comment]
Some (or all?) of this is addressed by #70 -- is there anything to be done to push this forward @hackajesse ? Is it still relevant and required for the MVP?

**Comment by jszwedko** [comment]
cc/ @jasonlally

**Comment by jasonlally** [comment]
Still relevant, but maybe we consolidate this to #65 and just close this issue. This is somewhat duplicative. I'll close as a duplicate.
