### ISSUE TITLE
Set alert frequency / methods for users

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#36]
Method: Email, SMS
Frequency: upon signup, few days before a storm, day of the storm, confirmation that things are clean(?)

**Comment by jszwedko** [comment]
I feel like this isn't required for the MVP (also given our discussion that this would be an intentional process taken by an admin, at least for now). Safe to remove the label or close this issue @hackajesse ?

**Comment by jszwedko** [comment]
cc/ @jasonlally

**Comment by hackajesse** [comment]
Would prefer to keep it open, but not attach to mvp.





On Sat, Dec 19, 2015 at 8:01 AM -0800, "Jesse Szwedko" <notifications@github.com> wrote:












cc/ @jasonlally

**Comment by jeanwalshie** [comment]
it sounds like we've set it up such that an email automatically goes out upon sign up for drains 1 and 2, but i'm still working on a system to send separate emails in advance of storms, after storms, etc.

**Comment by jeanwalshie** [comment]
SFPUC is sending storm alerts and other email notifications to adopters. i'm also going to change the copy on the site and in the initial emails to notify users that we'll be emailing them periodically, so i'm going to close this issue.
