### ISSUE TITLE
Are there drains outside this system managed/owned by another department/org?

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#39]
Ask Jean to ask John Seagrave

**Comment by jasonlally** [comment]
There are separate drains managed by Port, Jean is going to do some backgrounding to figure out who manages this data. We can possibly plan to roll these in later as it will be a pretty small subset of drains, so I don't think this has to be in the critical path for launch.

**Comment by jeanwalshie** [comment]
Apparently there are 4000+ drains owned by the Port and other entities. I say we leave the app as is for now.
