### ISSUE TITLE
Develop MVP list of changes and/or features

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#4]
_From @hackajesse on October 21, 2015 17:3_

_Copied from original issue: sfbrigade/adopt-a-drain.old#6_

**Comment by hackajesse** [comment]
@therebelrobot is this the right place to add a preliminary list of developer changes to create a backlog? Or do you want to create separate issues for those elsewhere?

**Comment by hackajesse** [comment]
_From @therebelrobot on October 21, 2015 18:8_

Go ahead and add the list here, each item will most likely be their own github issue for tracking/assignment. If you have time to separate each out, feel free to, otherwise I'll get to it either tonight or tomorrow.

**Comment by hackajesse** [comment]
_From @therebelrobot on October 21, 2015 18:9_

I've added the `MVP` tag for use if you do end up separating them out.

**Comment by afomi** [comment]
Hi @hackajesse, is there more to be done for this issue? 
It looks like a number of issues are tagged `MVP` now :+1:

**Comment by hackajesse** [comment]
@afomi this is really a reminder I assigned myself. I'll close once I finalize more specific issues.

**Comment by hackajesse** [comment]
@afomi if there's a better practice for doing ^^, I'm happy to change methods. :)

**Comment by jszwedko** [comment]
I think an issue to create new issues like this is fair -- as long as it has a defined end point which it feels like this does.

**Comment by jszwedko** [comment]
@hackajesse are you still brainstorming issues? Can this be closed now?

**Comment by hackajesse** [comment]
Yup! Ok to close





On Sat, Dec 19, 2015 at 7:34 AM -0800, "Jesse Szwedko" <notifications@github.com> wrote:












@hackajesse are you still brainstorming issues? Can this be closed now?

**Comment by jszwedko** [comment]
:clap: thanks!
