### ISSUE TITLE
If drains aren't adoptable, say why

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#40]
For example, if the SFPUC or another org owns/manages a drain, that drain should be claimed (either manually or permanently or something) by that org. Convey that clearly to the public when wanting to adopt a drain.

**Comment by jeanwalshie** [comment]
i think all the drains we show are adoptable.

**Comment by hackajesse** [comment]
@jeanwalshie close this issue if you feel it's addressed.

**Comment by jeanwalshie** [comment]
thanks -- as a newbie on github i've been a little hesitant to close issues, merge issues, reassign things, etc. but OK! :)
