### ISSUE TITLE
Differentiate colors btwn drains "adopted" and "adopted by you"

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#43]
They're too close (green vs blue)
Related to accessibility (color blindness??)

**Comment by jasonlally** [comment]
This is being worked on by SFPUC graphics team

**Comment by jasonlally** [comment]
They are also working on a drain icon for both drains to ocean/bay and combined sewer per #38

**Comment by jasonlally** [comment]
This is now done.
