### ISSUE TITLE
Make app accessible

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#44]
Have James Tyack go through it. Idk his github, but he's often at hacknight. I'm sure he'd be game to go through this and/or make suggestions for things we can look out for.

**Comment by jszwedko** [comment]
@therebelrobot were you able to talk to James?

**Comment by jeanwalshie** [comment]
i know we took colors/shapes into account when creating the icons (to make them distinguishable for the colorblind) but yes, we should think about this. http://www6.sfgov.org/index.aspx?page=73

**Comment by jszwedko** [comment]
Are there any actions to be taken for this issue? @jeanwalshie is there someone in the government that can review?

**Comment by jeanwalshie** [comment]
let me look into it, thanks. stay tuned.

**Comment by jszwedko** [comment]
:+1: thanks!

**Comment by jeanwalshie** [comment]
ok, it looks like we've done the best we can with this type of a webpage. the only thing we noticed is that the icons in the legend should be properly tagged with alt text, if possible.

**Comment by jszwedko** [comment]
:+1: I can add that text.

**Comment by jszwedko** [comment]
@jeanwalshie added the alt text in #123 -- let me know what you think!

**Comment by jeanwalshie** [comment]
@jszwedko -- i don't see the alt text on my icons in chrome. sorry, i'm sure it's something on my end. if they're there we can close this!

**Comment by jszwedko** [comment]
@jeanwalshie I think you are thinking about title text (which is the text that shows up when you hover over a picture with your mouse to provide more details), but for accessibility you set a different attribute, alt text, which screen readers pick up and read in place of the picture.

If you like, I can add title text too with the same content as the alt text.

Thanks!

**Comment by jszwedko** [comment]
Added title text in https://github.com/sfbrigade/adopt-a-drain/commit/0a879601eed764750e78921247397171dd41fa96 -- it'll need to be merged before publicly visible.

**Comment by jeanwalshie** [comment]
thanks @jszwedko --sorry, i didn't know the diff between alt text and title text! thanks for doing this.

**Comment by jszwedko** [comment]
No worries! Closing as the pull request was merged.
