### ISSUE TITLE
Post-storm email thanking folks for cleaning their drains

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#46]
V1: Thank people and say that we had X# new adoptions as a result of the app
V2 (post user confirmation they cleaned their drain): Thank people and share how many people cleaned their drains
VN (once we have data from DPW? on how much less flooding occurred during the most recent event when compared to other similar events w/out adoptadrain): Thank people, share how many people cleaned their drains, and share how much less flooding there was and cost savings as a result.

**Comment by jeanwalshie** [comment]
i would actually lump this in with all pre-and post-storm emails to adopters, which will be handled by me, including: thanking, reporting back, warning of storms, asking for feedback, etc.

**Comment by jeanwalshie** [comment]
i'm going to close this because i know how to go into the admin site and download contact info, and i will send emails as appropriate.

**Comment by jszwedko** [comment]
:+1: that is a good workaround until something is able to be added into the project.
