### ISSUE TITLE
Thank you gift for cleaning drains

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#47]
Likely needs the confirmation of a drain being cleared before implementation.
Also needs more PUC involvement / funding.

**Comment by afomi** [comment]
Cool idea :+1: 

I'm curious about a documented process to support the rollout/implementation of this.

**Comment by jeanwalshie** [comment]
this could be managed by SFPUC and yes, we'd need confirmation that the drain has been cleared (vs. simply adopted), which hinges on the tracking element we've talked about in #45. we could easily send out a tracking survey via email to adopters and provide a "gift" for those who respond. could also hold some sort of recognition event and safety training...?

**Comment by jeanwalshie** [comment]
closing this because plans are in the works to provide safety vests, rakes, gloves, etc. to drain adopters in fall 2016. we have also sent a survey and will continue to do so, and to incentivize and reward drain adopters.
