### ISSUE TITLE
Share how to get/access tools to clean the drain

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#48]
Once the PUC has tools available for lending, create a way for adopters to know how to access the tools.

**Comment by jeanwalshie** [comment]
i think we can build this into the copy somewhere (email when a person adopts, purple "what it means to adopt" box, follow-up email sent separately by SFPUC) once we have this in place. In the meantime there is the "Adopt a Street" program by Public Works, which we tell them about in email #2, that gives out tools. I'm fine closing this if y'all agree.

**Comment by jszwedko** [comment]
:+1: I'm fine with closing this until a lending program exists.
