### ISSUE TITLE
Email thanking user for adopting ANOTHER drain

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#49]

**Comment by hackajesse** [comment]
[Copy for the email in a Google Doc](https://docs.google.com/document/d/1mtugVFh8KFzTUtKCEm0RCdUpsX0enKdAR5aqWrI8fWo/edit)
Not ready yet - will update this comment when ready

**Comment by jasonlally** [comment]
This is implemented by #70
