### ISSUE TITLE
Collect user needs (user research)

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#5]
_From @hackajesse on October 21, 2015 17:3_

_Copied from original issue: sfbrigade/adopt-a-drain.old#5_

**Comment by jasonlally** [comment]
There may be an opportunity here to reach out to early adopters for user feedback. I talked to @ondrae briefly about this. Not pressing right now, but we should think about how to incorporate with soft launch.

**Comment by ondrae** [comment]
@moniquebt also offered to help find volunteers to set up and do this user testing. When do you think you'd need the help ready by?

**Comment by afomi** [comment]
+ :100: to user testing.  I thought there was an effort to collaborate with or expand Oakland's Civic User Testing Group.

**Comment by jeanwalshie** [comment]
update 1/8/15 we are currently doing user testing and adding issues as needed.

**Comment by ondrae** [comment]
Let me know if you need help from Code for America.

Andrew Hyder
Developer Advocate :: 2013 Fellow
@hackyourcity <http://twitter.com/hackyourcity>
