### ISSUE TITLE
Tweet out when someone new adopts a drain

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#50]
[] Ask user for twitter handle
[] Tweet from the PUC handle 30 minutes after the adoption happens (so the user has time to name the drain).
[] Use this copy: TBD

**Comment by hackajesse** [comment]
Could be really fun for the next iteration. @jeanwalshie what do you think about this?

**Comment by jeanwalshie** [comment]
yeah, totally. not sure how it would work though... how would we ask for twitter handle?

**Comment by jeanwalshie** [comment]
i'm gonna close this cuz when a drain adopter tweets that they've adopted a drain we (SFPUC) can retweet that.
