### ISSUE TITLE
Ask Jean about Adopt-a-Street Program

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#51]
http://sfdpw.org/index.aspx?page=1229

**Comment by hackajesse** [comment]
Jean is finding out more information from DPW.

**Comment by jszwedko** [comment]
@hackajesse any update on this? Is this issue still relevant?

**Comment by jszwedko** [comment]
cc/ @jasonlally

**Comment by jszwedko** [comment]
Bump @jasonlally @hackajesse

**Comment by jeanwalshie** [comment]
hey hey, we added Adopt a Street language to the 2nd email, and Public Works added (or will add) info on Adopt a Drain to their page, so this issue should be resolved.

**Comment by jeanwalshie** [comment]
oops, they haven't added the language yet so i'm re-opening this. i'll bug them about it.

**Comment by jszwedko** [comment]
Assigning to @jeanwalshie, let me know if you need anything from our end!

**Comment by jeanwalshie** [comment]
nothing needed on your end so i'm closing this, thanks!!
