### ISSUE TITLE
Clean up and modernize UI scaffolding - bootstrap 2 -> 3

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#52]
I was looking at the UI scaffolding used to layout the map and sidebar and it's simple enough, but uses table and table-cell layouts in a manner that makes it hard to make this friendly on mobile.

Without knowing the exact direction yet, it's simple enough to modernize the layout so it's a bit more flexible and mobile-friendly and uses Bootstrap 3 and it's dependencies.

This is just house cleaning to clear the way for more robust UI and UX changes.

**Comment by jszwedko** [comment]
We should contribute this sort of thing back upstream.

**Comment by jasonlally** [comment]
This issue is addressed by #53 so I'm going to close it. There are other things related to UI/UX we'll that this doesn't address, but those will be logged as separate issues.
