### ISSUE TITLE
Change favicon to a drain

### ISSUE THREAD

**Issue by jszwedko** [sfbrigade/adopt-a-drain#54]
favicon is currently a fire hydrant

**Comment by hackajesse** [comment]
@jszwedko Created a [set of variable sized v1 favicons](https://drive.google.com/open?id=0BxEflvO_7MDIWndHWGdXNmc5VTQ)

**Comment by jeanwalshie** [comment]
hey, the favicon is a yellow heart. didn't SFPUC submit a favicon that was in line with the green logo?

**Comment by jszwedko** [comment]
@jeanwalshie @jasonlally I never saw a favicon from the SFPUC, do one of you have it?

**Comment by jasonlally** [comment]
@jeanwalshie all I see in the files are the several logo options (horizontal and vertical) and 4 icons for the map.

**Comment by jeanwalshie** [comment]
checking on this - stay tuned!

**Comment by jeanwalshie** [comment]
![adopt a drain favicon_16-x-16](https://cloud.githubusercontent.com/assets/15933453/12308711/98c14852-b9fb-11e5-8037-9ac6c77e3ee5.png)
![adopt a drain favicon-32-x-32](https://cloud.githubusercontent.com/assets/15933453/12308710/98c0b05e-b9fb-11e5-8a53-d0397a2b0f65.png)

**Comment by jeanwalshie** [comment]
will these work? let me know if you need them in another format or something.

**Comment by jszwedko** [comment]
Nope, those are perfect!

**Comment by jszwedko** [comment]
Updated favicon in #118, thanks for the assets!

**Comment by jeanwalshie** [comment]
sorry, i'm still seeing the old yellow drain favicon, not the new green one...

**Comment by jszwedko** [comment]
@jeanwalshie you will probably have to do a hard refresh in your browser to clear the cache. Please let me know if this does not fix the issue.

**Comment by jeanwalshie** [comment]
@jszwedko  the correct icon is showing in explorer, but not chrome, for some reason. i cleared the cache and double checked with a colleague...

**Comment by jszwedko** [comment]
I'm also using chrome -- you should be able to do a hard refresh via `ctrl-F5` on Windows or `cmd-F5` on OSX. Please let me know if this still doesn't resolve it.

**Comment by jeanwalshie** [comment]
it works!

**Comment by jszwedko** [comment]
Woo! :+1:
