### ISSUE TITLE
Remove phone number fields?

### ISSUE THREAD

**Issue by jszwedko** [sfbrigade/adopt-a-drain#56]
Currently there is a field for both home and mobile phone number. Do we need/want to collect this information?

cc/ @hackajesse

**Comment by jszwedko** [comment]
Bump @jasonlally @hackajesse

**Comment by jasonlally** [comment]
Jean wants to remove these. Since they aren't required, we can just hide them in the interface.

**Comment by jszwedko** [comment]
Closed by #82
