### ISSUE TITLE
Report an offensive drain name

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#57]
Ref: #12

**Comment by howdoicomputer** [comment]
As a note, the Thing model has its name attribute guarded by the [obscenity gem](https://github.com/tjackiw/obscenity). 

See: https://github.com/sfbrigade/adopt-a-drain/blob/production/app/models/thing.rb#L14

**Comment by jszwedko** [comment]
Yeah, we did add that simple filter, but I feel like the only real way to combat this sort of thing is crowdsourcing the offensive names as filters are easy to work around.

**Comment by howdoicomputer** [comment]
Oh, yeah, for sure. I thought I would just put that in this thread for posterity.

**Comment by jszwedko** [comment]
True that :+1:

**Comment by jeanwalshie** [comment]
is there a way i can see the list of words that are in the "profanity filter"? 
also, thinking of closing this because it hasn't become an issue...

**Comment by jszwedko** [comment]
@jeanwalshie you can find the lists here:

* https://github.com/tjackiw/obscenity/blob/master/config/blacklist.yml
* https://github.com/tjackiw/obscenity/blob/master/config/international.yml

**Comment by jeanwalshie** [comment]
thanks @jszwedko! 

that gave me a chuckle. I'm going to close this issue.
