### ISSUE TITLE
Mobile phones zoom to input on focus

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#59]
Related to #19, there's an issue on mobile phones where they zoom in to make text bigger on form inputs. The simple solution to this is to set the text size on inputs at a big enough size to avoid the viewport zooming.

Also, javascript autofocuses to the input, I think it just makes sense to remove that interaction. I think people won't mind the extra click to search the map and it'll make the interface more sensible on mobile.

**Comment by jszwedko** [comment]
Closed by #59, thanks again!
