### ISSUE TITLE
Identify users (internal and external)

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#6]
_From @hackajesse on October 21, 2015 17:3_

_Copied from original issue: sfbrigade/adopt-a-drain.old#4_

**Comment by jszwedko** [comment]
@hackajesse can you provide more context here? I'm not sure I understand the intention.

**Comment by hackajesse** [comment]
I guess this is really, "Create personas" for the project. Not an engineering issue. 
How should I make it clearer when I'm creating an issue, but it's not related to engineering? I'm trying to use Github (and a lot of Zenhub features) to manage the project. I started using labels more religiously as a first attempt. Thoughts @jszwedko ?

**Comment by jszwedko** [comment]
@hackajesse aaah! No worries, I think labels you have are good. I completely missed this was assigned to you which would have implied to me that it wasn't engineering related (at least yet) -- overall I think the process we have going on now is working pretty well.

**Comment by jszwedko** [comment]
@hackajesse any update on this? Just wondering if it should still be wrapped under the MVP label.

**Comment by jszwedko** [comment]
Also cc/ @jasonlally

**Comment by jasonlally** [comment]
I think this will happen as part of the rollout. I'm going to remove the flag but keep the issue open.

**Comment by hackajesse** [comment]
Would like to remove it from the MVP. This wod be a great exercise for the new Adopta team (whenever they coalesce).





On Sat, Dec 19, 2015 at 9:57 AM -0800, "Jason Lally" <notifications@github.com> wrote:












I think this will happen as part of the rollout. I'm going to remove the flag but keep the issue open.

**Comment by jeanwalshie** [comment]
hi all, just wondering what you mean by "create personas" and identify users.

**Comment by hackajesse** [comment]
@jeanwalshie this is really a way to help us differentiate between someone who is kinda flakey and someone who is dutiful, for example. A dutiful person will not need much in terms of reminders and will likely engage regularly. A flakey person might need consistent reminders to both clean and report (when that feature happens). How can we account for different types of people? By creating personas using user research and by thinking about these in advance. [Personas on Wikipedia](https://en.wikipedia.org/wiki/Persona_(user_experience))

**Comment by jeanwalshie** [comment]
i'm thinking we can close this since the app has launched, is developing into a full-scale SFPUC program, and has real users!
