### ISSUE TITLE
Load a subset of drains

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#64]
Still working on documentation for drain_type, but at a high level, it appears that the following are the primary relevant ones:

Wetwell; Storm Water Inlet Drain; Area Drain, used in Mission Bay; Drain Box; Trench Drain; Catch Basin Drain; Drop Inlet

The balance of drain types are either on freeways (don't want folks adopting there), on tracks or otherwise inaccessible (MTA or Caltrans).

@afomi do you want me to modify the query to select only those? Or do you want to pick that off?

You can use SoQL and return a csv https://dev.socrata.com/docs/queries.html

**Comment by jasonlally** [comment]
Actually, I'll check in before we do any work here, it might be only 2 or 3 of those remaining categories. I'm waiting on verification.

**Comment by jasonlally** [comment]
Ok, have clarification on categories. @afomi I can adjust the rake task for loading drains to only select the appropriate categories. I'll just push my changes to that branch, if that works?

I won't touch anything regarding the schema adjustments in #17, I'll just add the categories to the dataset query.

**Comment by afomi** [comment]
Sounds good to me. We can chat more tonight.

On Wed, Dec 2, 2015 at 10:31 AM, Jason Lally <notifications@github.com>
wrote:

> Ok, have clarification on categories. @afomi <https://github.com/afomi> I
> can adjust the rake task for loading drains to only select the appropriate
> categories. I'll just push my changes to that branch, if that works?
>
> I won't touch anything regarding the schema adjustments in #17
> <https://github.com/sfbrigade/adopt-a-drain/issues/17>, I'll just add the
> categories to the dataset query.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sfbrigade/adopt-a-drain/issues/64#issuecomment-161391075>
> .
>



-- 
Ryan Wold
(707) 673-6722

**Comment by jasonlally** [comment]
Thanks @afomi this is addressed by #24 closing
