### ISSUE TITLE
Edit text in modal popup so people can review what they're committing to (accentuate safety)

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#65]
Related to #34 we should add a very simple button at the top of sign up that people can click on to review what it means to adopt a drain.

We can wait until we have some approved copy to implement, but it'll just mimic the same pattern used for the Terms of Service link, so shouldn't be hard to implement.

Clearly convey who users should contact if they can't clear their drain on the homepage

**Comment by jszwedko** [comment]
@jasonlally should this just use the same copy as the e-mail that is sent when the user adopts their first drain?

**Comment by jszwedko** [comment]
Closed by #65

**Comment by jeanwalshie** [comment]
One user didn’t find it obvious that the purple box was clickable (“click here to find out what it means to adopt”). She suggested linking to the “what it means to adopt” language/box in the pop up box that appears when someone clicks on a drain where it says “Sign in to adopt this drain.” Not sure if this is the best solution, or if this is even needed.

**Comment by jszwedko** [comment]
Added link to modal in #114

**Comment by jeanwalshie** [comment]
i notice that once a user is signed in the purple box disappears and so does the link in the pop up about what it means to adopt a drain. Is this a mistake? once a user is logged in there is no more information about what they are committing to... thoughts?

**Comment by jszwedko** [comment]
That is intentional looking at the code, it's easy to add if we want it though -- it feels like a good thing. I'll open a new issue to track that.

**Comment by jszwedko** [comment]
Opened #117, thanks for bringing this up @jeanwalshie !

**Comment by jeanwalshie** [comment]
hi all, i reopened this because we got feedback that the safety message needed to be more prominent. the revised text is [here](https://docs.google.com/document/d/1PVGZ-B-etARxIyMxNx0yMjtcNywIrIZlFVk-RS35C3s/edit).

**Comment by jszwedko** [comment]
Updated in #132, now looks like:

![2016-01-29-194248_1012x707_scrot](https://cloud.githubusercontent.com/assets/316880/12693505/7dcfdd3e-c6c0-11e5-98ed-1844b5c7bddf.png)

**Comment by jszwedko** [comment]
Didn't see #130 before I created mine, merged #130 so this should be good

**Comment by jszwedko** [comment]
@jeanwalshie feel free to close this if it looks good to you now!

**Comment by jeanwalshie** [comment]
@jszwedko this looks great, but now i'm thinking we should add this legal text at the end from the other copy just to be safe (and consistent): 
"Remember, the City and County of San Francisco won't be held responsible for anything that happens to you or others in service of maintaining your drain. Please be careful!"
(Sorry i didn't catch this earlier!)

**Comment by jszwedko** [comment]
@jeanwalshie no worries! Added in #139, looks like:

![2016-02-03-210200_881x608_scrot](https://cloud.githubusercontent.com/assets/316880/12806284/658036aa-cab9-11e5-8dbe-e64987c035dc.png)

**Comment by jeanwalshie** [comment]
Awesome @jszwedko thank you! This looks great, but I don't see the language in the app...?

**Comment by jszwedko** [comment]
@jeanwalshie I hadn't merged it yet since I wanted to see your thoughts first, but I'll push it through now!

**Comment by jeanwalshie** [comment]
hurray, thanks!
