### ISSUE TITLE
Incorporate link to PUC page about drains that go to the ocean/bay into the user interface

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#66]
Jean is going to look into creating copy about the difference between drains that go into the combined sewer system and those that drain to the bay or ocean. 

This educational copy will live on the SFPUC website where they already have information about the system. 

Once we have icons and make necessary changes (see #38) to surface those differences, we will link users to that copy (and link folks back to adopt a drain) with some simple legends and labels on the popups. (e.g. "This drain goes to the bay or ocean - learn more")

@hackajesse do you know Jean's handle?

**Comment by hackajesse** [comment]
@jasonlally @jwalshie I think...



– 
Jesse Biroscak

jesse.biroscak@gmail.com

c. 415.439.3164


[Li] [Tw]

**Comment by jasonlally** [comment]
@jeanwalshie This is the issue related to creating copy on the PUC website that describes the difference between drains and the importance of caring for a drain that goes to the ocean/bay.

Once you have a link, add it to this thread and then we can add it as a link where folks can learn more when adopting those types of drains.

**Comment by jeanwalshie** [comment]
http://sfwater.org/index.aspx?page=152

Check it out. I modified an existing page on our site with info about catch basins vs. storm drains. I'll continue to make edits to this page but the link will remain the same.

**Comment by jasonlally** [comment]
Great! We'll add this link to the interface after we have #100 in place. I'll leave this issue open until we do so and update the issue title to reflect the updated task.

**Comment by jasonlally** [comment]
Based on our conversation, I think the simplest thing to do will be to include the informational link on the info window for the ocean/bay drain types, in addition to indicating the drain types through the legend and on the map via the icon.

**Comment by jeanwalshie** [comment]
let's please use this link instead:  http://sfwater.org/index.aspx?page=399

**Comment by jeanwalshie** [comment]
we'll also need to add the storm drain icon to the legend. (i didn't see this specifically called out.)

**Comment by jszwedko** [comment]
@jasonlally reminder to push what you have when you have a moment. I can pick up from there.

**Comment by jasonlally** [comment]
@jszwedko - sorry it took me so long, I pushed today #119

**Comment by jszwedko** [comment]
No worries! I'll take a look.

**Comment by jasonlally** [comment]
Addressed by #119
