### ISSUE TITLE
Test email functionality

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#68]
Pending pull request #23 we want to test the functionality with the email copy edited by Jean.

**Comment by jszwedko** [comment]
Merged #23 and verified that I got an e-mail after adopting a drain that looked like:

```
Hello Jesse,

Thank you for adopting a drain at 1150 Sanchez Street!

The Adopt-a-Drain Team
```

**Comment by afomi** [comment]
thanks @jszwedko :+1:

**Comment by jszwedko** [comment]
Closing this since e-mails work thanks to @afomi and we already have another issue regarding the updated copy (#14).
