### ISSUE TITLE
Deploy base adopta installation

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/adopt-a-drain#7]
_From @hackajesse on October 21, 2015 17:2_

Based on the backgrounding, we need to figure out which fork is best to start from and where it will go

_Copied from original issue: sfbrigade/adopt-a-drain.old#3_

**Comment by hackajesse** [comment]
@therebelrobot would you say this is finito?

**Comment by afomi** [comment]
@hackajesse, I think this is complete.  We opted to fork CfA's most recent version, which was significantly more current that a fork I found that Oakland was running.
