### ISSUE TITLE
Any logged in user can send a reminder to any other adopter

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#79]
I'm not sure if this was a "feature" on the original platform, but I'm going to consider a "bug"  We just want admins to be able to send reminders, not any registered user. 

The simple fix here is to remove the button. Oakland doesn't have this feature.

![send_reminder](https://cloud.githubusercontent.com/assets/534176/11904721/e9dceb2c-a576-11e5-9dae-03b1e2e4724f.PNG)

**Comment by jszwedko** [comment]
Weird, I never noticed that button. I just sent you a reminder to test the bug.

**Comment by jasonlally** [comment]
Yeah, I got an email. I think this may be the default for Adopt A Hydrant. Simple enough to remove. Maybe there's a way to leverage this though for admin users to send?

**Comment by jasonlally** [comment]
Merged PR, closing
