### ISSUE TITLE
Jean review triggered emails

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#80]
#70 implemented adoption emails. Need to check with Jean about the content.

**Comment by jasonlally** [comment]
Jean reviewed these and submitted updates. Links to the updated content are in their related issue. Closing this.

**Comment by jeanwalshie** [comment]
hi all, i'm reopening this because i made slight changes to the [1st email copy ](https://docs.google.com/document/d/1ogprm41vY17Wj-rSjOds7UOJDQGtv6t4oiswYEDTtAg/edit)to accentuate the safety message, per staff request. sorry and thank you!!!

**Comment by jszwedko** [comment]
Updated in #131 -- note that we are still using plain text e-mails so things like bold text, italics, and links aren't possible.

Let me know if it looks good!

**Comment by jasonlally** [comment]
@jeanwalshie The copy looked right to me...look okay to you?

**Comment by jeanwalshie** [comment]
@jasonlally @jszwedko looks great! sorry, i forgot about the HTML/plain text issue. thanks!!

**Comment by jszwedko** [comment]
No worries! We can definitely switch to HTML e-mails since it seems like there is more of a need for them now (additional styling), but let's get these changes in first.

**Comment by jszwedko** [comment]
Closed via #131 

Opened #138 to switch to HTML e-mails.
