### ISSUE TITLE
Need better meta for social sharing

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#81]
Currently there's not a meta description for the site, so Facebook picks up the legal terms and conditions. Probably not the initial tone we want to set :wink: 

![facebook](https://cloud.githubusercontent.com/assets/534176/11909157/dc65222c-a597-11e5-9ee2-efc2f95438b0.PNG)

**Comment by jszwedko** [comment]
@jasonlally had to make a couple of adjustments (you can see here https://github.com/sfbrigade/adopt-a-drain/compare/83927f6834de9c5e6aba437fb214431758e82329...sfbrigade:production) but this looks good now. Good catch!
