### ISSUE TITLE
Update social media sharing copy

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#89]
Jean's modified the copy here: https://docs.google.com/document/d/1kE-h5abTWVZvG9HOt_o4Ipy9N8PJtQuKToboPbppdkw/edit

Just need to update.

**Comment by jszwedko** [comment]
Addressed by #96

**Comment by jasonlally** [comment]
Have some minor updates in the copy above to website meta and the email. Reopening.
