### ISSUE TITLE
Pass a default thing name to the info window when user has not named the drain

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#92]
If the drain name is blank, then it looks like this:

![missing_name](https://cloud.githubusercontent.com/assets/534176/12023877/01d42b12-ad53-11e5-8f9b-e8d190607ffd.PNG)

We should just pass something using the thing name when we detect no thing name. For example: This drain has been adopted...

**Comment by jszwedko** [comment]
Addressed by #99
