### ISSUE TITLE
Fix reset password workflow

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/adopt-a-drain#93]
Reset password is broken in a couple of (easily fixable) ways:

- [x] No visual feedback that a link was successfully sent. This is likely because the flash notice was removed for this, easy enough to put back in.
- [x] Wrong domain included in the link it's http://adoptadrain.org instead of our domain
- [x] Email subject just says "Reset Password Instructions" should be a bit more explicit that it's for Adopt a Drain SF.
- [x] Email is from noreply@adoptadrain.com
- [x] The Reset password page doesn't reflect the brand at all, may decrease trust. Would be ideal to simply have that wrapped in the sidebar, but not sure how easy that is.
![edit_password](https://cloud.githubusercontent.com/assets/534176/12028617/d960fc6e-ad8e-11e5-9350-4575e8809ddb.PNG)

**Comment by jeanwalshie** [comment]
Yes, agree that the reset password email is not clearly tied to Adopt a Drain SF. In addition to changing the subject line, I'd like to change the email copy to "Someone has requested a link to change your password for Adopt a Drain SF"

**Comment by jszwedko** [comment]
@jasonlally what e-mail address should this come from? Assuming `no-reply@sfwater.org`, but let me know if not.

**Comment by jeanwalshie** [comment]
that works for me, thanks.

**Comment by jasonlally** [comment]
Yes, no-reply@sfwater.org works
