### ISSUE TITLE
Create SPF record for sfwater.org

### ISSUE THREAD

**Issue by jszwedko** [sfbrigade/adopt-a-drain#97]
Whitelist sendgrid as per https://sendgrid.com/docs/Glossary/spf.html to reduce probability it will wind up in spam.

**Comment by jszwedko** [comment]
@jasonlally I think you'll need to handle this? Or at least coordinate handling.

**Comment by jszwedko** [comment]
@jeanwalshie this may be something that you can help with as well -- it'll need to be handled by the owners of adoptadrain.sfwater.org.

Basically we want to add sendgrid to the whitelist of domains that can send e-mail on adoptadrain.sfwater.org's behalf to help reduce the likelihood that e-mails from the domain will be marked as spam.

**Comment by jeanwalshie** [comment]
yes, checking with our IT staff on this. stay tuned.

**Comment by jasonlally** [comment]
I got confirmation that this was created.
